In [1]:
import numpy as np

# 패딩 방식

원하는 크기의 0행렬을 만들어, 원배열을 덮어씌운다

In [6]:
a = np.array([[1,2], [3,4]])
b = np.zeros((3,3))
print('a : \n', a)
print('b : \n', b)
b[:2, :2] = a
print('padding a : \n', b)

a : 
 [[1 2]
 [3 4]]
b : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
padding a : 
 [[1. 2. 0.]
 [3. 4. 0.]
 [0. 0. 0.]]


# 패딩

* np.pad() : 원하는 패딩폭을 지정함
    * 패딩폭을 정수로 넣으면 해당 정수만큼의 패딩폭이 생성
    * 튜플로 넣으면 조금 다름(예시 볼것)
    
    * 패딩방식 
        * constant : default (0으로 채움)
        * edge : 마지막 만나는 원소로 채움
        * minimun : 만나는 원소중 가장 작은 원소로 채움(만나는 원소가 없으면 가장 작은 원소로)
        * maximun : 만나는 원소중 가장 큰 원소로 채움(만나는 원소가 없으면 가장 큰 원소로)
        * mean : 평균값으로
        * median : 중앙값으로

In [17]:
a = np.array([[1,2], [3,4]])

print('패딩폭 1')
print(np.pad(a, 1))

print('패딩폭 2')
print(np.pad(a, 2))

print('패딩폭 (0, 1)')
print(np.pad(a, (0,1)))

print('패딩폭 (1, 0)')
print(np.pad(a, (1,0)))

print('패딩폭 (1, 1)')
print(np.pad(a, (1,1)))

print('패딩폭 (1, 2)')
print(np.pad(a, (1,2)))

print('edge 패딩')
print(np.pad(a, 2, "edge"))

print('maximum 패딩')
print(np.pad(a, 2, "maximum"))

print('minimum 패딩')
print(np.pad(a, 2, "minimum"))

print('mean 패딩')
print(np.pad(a, 2, "mean"))

print('median 패딩')
print(np.pad(a, 2, "median"))

패딩폭 1
[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]
패딩폭 2
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 1 2 0 0]
 [0 0 3 4 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
패딩폭 (0, 1)
[[1 2 0]
 [3 4 0]
 [0 0 0]]
패딩폭 (1, 0)
[[0 0 0]
 [0 1 2]
 [0 3 4]]
패딩폭 (1, 1)
[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]
패딩폭 (1, 2)
[[0 0 0 0 0]
 [0 1 2 0 0]
 [0 3 4 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
edge 패딩
[[1 1 1 2 2 2]
 [1 1 1 2 2 2]
 [1 1 1 2 2 2]
 [3 3 3 4 4 4]
 [3 3 3 4 4 4]
 [3 3 3 4 4 4]]
maximum 패딩
[[4 4 3 4 4 4]
 [4 4 3 4 4 4]
 [2 2 1 2 2 2]
 [4 4 3 4 4 4]
 [4 4 3 4 4 4]
 [4 4 3 4 4 4]]
minimum 패딩
[[1 1 1 2 1 1]
 [1 1 1 2 1 1]
 [1 1 1 2 1 1]
 [3 3 3 4 3 3]
 [1 1 1 2 1 1]
 [1 1 1 2 1 1]]
mean 패딩
[[2 2 2 3 2 2]
 [2 2 2 3 2 2]
 [2 2 1 2 2 2]
 [4 4 3 4 4 4]
 [2 2 2 3 2 2]
 [2 2 2 3 2 2]]
median 패딩
[[2 2 2 3 2 2]
 [2 2 2 3 2 2]
 [2 2 1 2 2 2]
 [4 4 3 4 4 4]
 [2 2 2 3 2 2]
 [2 2 2 3 2 2]]
