In [1]:
import numpy as np
from pprint import pprint

# 색인검색
대괄호 사용해 원소를 조회함.

In [2]:
a = np.array(np.arange(10))

print('a : ', a)
print('a[0] : ', a[0])
print('a[-1] : ', a[-1])
print()

b = a.reshape(2,5)
print('b : \n', b)
print('b[0] : ', b[0])
print('b[0, 3] : ', b[0, 3])




a :  [0 1 2 3 4 5 6 7 8 9]
a[0] :  0
a[-1] :  9

b : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
b[0] :  [0 1 2 3 4]
b[0, 3] :  3


# 슬라이스 검색

* a:b =>  a 부터 b까지
* a: => a부터 ~ 까지
* :b => ~b까지
* ::a => 첫번째 원소부터 a의 간격만큼만
* a::b => a번째 원소부터 b의 간격만큼 뛰어서
* ... => 생략기호
    * ex) [:, :, :, :, 0] == [..., 0]

In [3]:
a = np.array(np.arange(1,10)).reshape(3,3)
b = np.array(np.arange(1,20))
c = np.array(np.arange(16)).reshape(2,2,2,2)

print('a : \n', a)
print('a[:, 2] : ', a[:, 2])
print('a[2, :] : ', a[2, :])
print()

print('b : ', b)
print('b[::2] : ', b[::2])
print('b[1::3] : ', b[1::3])
print()

print('c : \n', c)
print()
print('c[..., 1] : \n ', c[..., 1])
print()
print('c[:, :, :, 1] : \n ', c[:, :, :, 1])




a : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
a[:, 2] :  [3 6 9]
a[2, :] :  [7 8 9]

b :  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
b[::2] :  [ 1  3  5  7  9 11 13 15 17 19]
b[1::3] :  [ 2  5  8 11 14 17]

c : 
 [[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]

c[..., 1] : 
  [[[ 1  3]
  [ 5  7]]

 [[ 9 11]
  [13 15]]]

c[:, :, :, 1] : 
  [[[ 1  3]
  [ 5  7]]

 [[ 9 11]
  [13 15]]]


# 논리식

논리식 검색을 할때 논리식 배열과 검색을 하려는 배열의 행,열이 일치해야함.  
a < 4 => a 배열에서 4보다 작은 값의 위치에는 True, 
4보다 큰 값의 위치에는 False가 들어감.  

a[bool 배열]

**논리식 검새을 한 결과는 메모리를 공유하지 않는다!!**

* .nonzero() : 0이 아닌 원소의 인덱스를 리턴한다.

## 주의사항
논리연산은 and, or, not을 사용하지 못한다.  
대신 &, |, ~ 를 사용해야함.
0은 False로 취급됨.  => 즉 0 & 0 은 False임.



In [4]:
a = np.random.randn(4,5)
print('a < 0 : \n', a < 0)
print()
a[a < 0] = 999
print('a : \n', a)

a = np.array(np.arange(2, 10))
print('a.nonzero() : ', a.nonzero())

a = np.array(1)
print('np.logical_and(a , a) : ', np.logical_and(a , a))

a < 0 : 
 [[False False  True  True False]
 [False  True  True False  True]
 [False False  True  True False]
 [False False False  True  True]]

a : 
 [[1.37208431e+00 4.75167380e-01 9.99000000e+02 9.99000000e+02
  1.70125115e+00]
 [1.22987553e-01 9.99000000e+02 9.99000000e+02 5.37746094e-01
  9.99000000e+02]
 [6.87876110e-03 1.40445059e-01 9.99000000e+02 9.99000000e+02
  1.10958950e+00]
 [2.17536053e-01 8.93570380e-01 1.16631289e-02 9.99000000e+02
  9.99000000e+02]]
a.nonzero() :  (array([0, 1, 2, 3, 4, 5, 6, 7]),)
np.logical_and(a , a) :  True


# 팬시검색

인덱스를 통해 배열을 검색한다.
**단 이때 메모리는 공유하지 않는다.**

In [5]:
a = np.array(np.arange(20, 40))
b = np.array(np.arange(9,13))
c = np.array([1,3,3,5])
print('a : ', a)
print('a[b] : ', a[b])
print('a[c] : ', a[c])
print('np.may_share_memory(a, a[b]) : ', np.may_share_memory(a, a[b]))
print('np.may_share_memory(a, a[:]) : ', np.may_share_memory(a, a[:]))

a :  [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
a[b] :  [29 30 31 32]
a[c] :  [21 23 23 25]
np.may_share_memory(a, a[b]) :  False
np.may_share_memory(a, a[:]) :  True


# 다차원 배열에서 팬시 검색

검색하려는 인덱스를 넣어 검색하면 된다.

In [6]:
a = np.array(np.arange(20, 40)).reshape(5, 4)
print('a : \n', a)
print()

print('a[[3,2]] : \n', a[[3,2]])
print()

print('a[[3,2], [0,1]] : \n', a[[3,2], [0,1]])    #3행 0열과, 2행 1열의 원소를 리턴한것임.

a : 
 [[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]

a[[3,2]] : 
 [[32 33 34 35]
 [28 29 30 31]]

a[[3,2], [0,1]] : 
 [32 29]


# 다차원 팬시 검색 (추가필요)

In [7]:
a = np.array(np.arange(20, 40)).reshape(5, 4)
print('a : \n', a)
print(a[[2,1], [3,3]])
print(a[[[2,1], [3,3]], [1,2]])

a : 
 [[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]
[31 27]
[[29 26]
 [33 34]]


# 팬시와 슬라이싱 혼용

In [8]:
a = np.array(np.arange(20, 40)).reshape(5, 4)
print('a : \n', a)
print(a[1:3, [2,3]])

a : 
 [[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]
[[26 27]
 [30 31]]


# 배열 축소 및 확대

## 차원  확대(추가 공부 필요)

## 2차원 배열을 3차원 배열로 만드는방법

```python
a.shape
>>> (m, n)
a = a.reshape(m, n, 1)
a.shape 
>>> (m, n, 1)
a = a[:, :, [0,0,0]]
```

In [9]:
a = np.array(np.arange(27)).reshape(9,3)
print(a.shape)
a = a[:, [[0,0,0], [1,1,1], [2,2,2]] , np.newaxis]
print(a.shape)



(9, 3)
(9, 3, 3, 1)
