In [1]:
import numpy as np

# 브로드캐스팅

형태가 맞지 않아도 일정 조건이 맞으면 브로드 캐스팅을 통해 연산을 가능하게 함.  
ex) (2, 5)행렬과 와 (5,)벡터는 연산이 가능함.  
**단 일정 조건이 맞아야함**   
**적어도 행과, 열이 하나는 맞아야함** 
=> 만약 (2,5)와 (6,)이 연산을 하려 한다면 예외가남

* np.braodcast_to() : 특정 shape으로 브로드캐스팅한다 (조건 맞아야함)
    * 이또한 (5,) 벡터를 (2,6)으로 늘리는것은 불가능 => (n,5)만 가능


In [17]:
a = np.array(np.arange(10)).reshape(2,5)
b = np.array(np.arange(10,15))

print('a : \n', a)
print('b : \n', b)
print('a + b : \n', a + b)

c = np.broadcast_to(b, (2,5))
d = np.broadcast_to(10, (2,5))
print('c : \n', c)
print('d : \n', d)

a : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
b : 
 [10 11 12 13 14]
a + b : 
 [[10 12 14 16 18]
 [15 17 19 21 23]]
c : 
 [[10 11 12 13 14]
 [10 11 12 13 14]]
d : 
 [[10 10 10 10 10]
 [10 10 10 10 10]]


# 행벡터, 열벡터 브로드캐스팅 확장

우리가 자주 사용하는것은 열벡터이지만, 다차원 벡터는 주로 행벡터 중심으로 만들어짐.

만약 a = [1,2] 인 행벡터와 b = [3,4]^T인 열벡터가 있다하면 이 둘은 어떻게 계산될까??  

a가 b의 차원에 맞춰 [[1,2], [1,2]]로 확장되고, b가 a의 차원에 맞춰 [[3,3], [4,4]]로 확장되어 계산된다.


In [22]:
a = np.array([1,2])
b = np.array([3,4]).reshape(2,1)

print(a)
print(b)
print(a + b)

[1 2]
[[3]
 [4]]
[[4 5]
 [5 6]]
