In [139]:
import numpy as np
from pprint import pprint

# 변형 및 변경함수

* .reshape() : 변형하려는 원소 개수가 맞아야 변형이 가능하다.
    * 파라미터로 -1을 넣을경우 자동으로 형상을 맞춰준다
        * 단 -1는 최종 한번만 사용 가능하다. (2, -1, -1)은 불가능!
        
* np.resize() : 기존 원소를 사용하여 새로운 형태로 채운다
* .resize() : 기존 원소를 재사용하지 않으며 남은 자리는 0으로 채운다
    * refcheck : 기존 배열의 형태를 체크한다 (False로 할시 형태 상관없이 리사이즈 가능)
        
* np.meshgrid() : 두개의 벡터를 넣어  두 벡터의 차원만큼의 새로운 행렬을 만들어 리턴함.
    * a는 차원 3, b 는 차원 5일때 (a,b)를 넣으면 5행, 3열의 행렬이 나옴.
        * 이때 먼저 사용된 파라미터 a는 수평확장, b는 수직확장 된다.
        
* np.compress() : 특정 조건 추출 (팬시 검색과 비슷함.)
    * 0 : False, 1 : True
        * axis가 없다면 입력받은 배열을 flatten하여 결과를 리턴해준다.
        
* np.squeeze() : 1인 차원 축소

In [80]:
a = np.array(np.arange(20))

b = a.reshape(2,2,5)
c = a.reshape(5, -1).copy()
d = np.arange(3)

print('b : \n', b)
print('c : \n', c)

c.resize((6, 6))
print('resize c to (6,6) : \n', c)

d.resize((2, 8))

print('d : ', d)

a = np.arange(3)
b = np.arange(5)

a, b = np.meshgrid(a, b)
print('a : \n', a)

print('b : \n', b)

a = np.array([[1,2], [3,4], [5,6]])

print('np.compress([0,1,1], a) : ', np.compress([0,1,1], a))
print('np.compress([0,1], a, axis=0) : ', np.compress([0,1], a, axis=0))
print('np.compress([0,1],a, axis=1) : \n', np.compress([0,1],a, axis=1))

a = a.reshape(1,6,1)
print('a.shape : ', a.shape)

print('np.squeeze(a).shape : ', np.squeeze(a).shape)
print('np.squeeze(a, axis=0).shape : ', np.squeeze(a, axis=0).shape)
print('np.squeeze(a, axis=2).shape : ', np.squeeze(a, axis=2).shape)

b : 
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
c : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
resize c to (6,6) : 
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]]
d :  [[0 1 2 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
a : 
 [[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]
b : 
 [[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]
np.compress([0,1,1], a) :  [2 3]
np.compress([0,1], a, axis=0) :  [[3 4]]
np.compress([0,1],a, axis=1) : 
 [[2]
 [4]
 [6]]
a.shape :  (1, 6, 1)
np.squeeze(a).shape :  (6,)
np.squeeze(a, axis=0).shape :  (6, 1)
np.squeeze(a, axis=2).shape :  (1, 6)


# 원소 반복

* np.repeat() : 원소를 반복한다.

* np.tile() : 배열을 원하는 모양만큼 확장시킨다

In [93]:
a = np.arange(5)
b = np.array([[1,2], [3,4]])

print('np.repeat(a, 2) : ', np.repeat(a, 2))
print('np.repeat(b, 2) : ', np.repeat(b, 2))
print('np.repeat(b, 2, axis=0) : \n', np.repeat(b, 2, axis=0))
print('np.repeat(b, 2, axis=1) : \n', np.repeat(b, 2, axis=1))

print('np.tile(b, 2) : ', np.tile(b, 2))
print('np.tile(b, [2,2]) : \n', np.tile(b, [2,2]))
print('np.tile(b, [2,2,2]) : \n', np.tile(b, [2,2,2]))



np.repeat(a, 2) :  [0 0 1 1 2 2 3 3 4 4]
np.repeat(b, 2) :  [1 1 2 2 3 3 4 4]
np.repeat(b, 2, axis=0) : 
 [[1 2]
 [1 2]
 [3 4]
 [3 4]]
np.repeat(b, 2, axis=1) : 
 [[1 1 2 2]
 [3 3 4 4]]
np.tile(b, 2) :  [[1 2 1 2]
 [3 4 3 4]]
np.tile(b, [2,2]) : 
 [[1 2 1 2]
 [3 4 3 4]
 [1 2 1 2]
 [3 4 3 4]]
np.tile(b, [2,2,2]) : 
 [[[1 2 1 2]
  [3 4 3 4]
  [1 2 1 2]
  [3 4 3 4]]

 [[1 2 1 2]
  [3 4 3 4]
  [1 2 1 2]
  [3 4 3 4]]]


# 배열 결합

* np.concatenate([]) : 배열들을 결합한다
    * axis를 지정하지 않으면 수직으로 연결, axis가 있다면 각 axis에 맞춰 연결함.
    
* np.stack() : 축을 지정해 쌓는다.
    * concatenate와 다른점은 배열을 그대로 유지한채로 쌓는다. concatenate는 배열의 모양만을 유지하여 결합하는 느낌이고 stack은 배열을 통째로 쌓는다는 느낌이다.
* np.vstack() : 축을 지저앟여 쌓는다. (vertical 세로)
* np.hstack() : 축을 지정하여 쌓는다. (horizontal 가로)
* np.dstack() : 축을 확대한다. 즉 가장 낮은 차원에서 원소끼리 결합함
    * 2차원 배열을 3차원으로 만들때 사용

In [130]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[8,7,6], [5,4,3]])
print('a : \n', a)
print('b : \n', b)
print()
print('np.concatenate([a,b]) : \n', np.concatenate([a,b]))
print('np.concatenate([a,b], axis=1) : \n', np.concatenate([a,b], axis=1))
print()

print('np.stack([a,b]) : \n', np.stack([a,b]))
print('np.stack([a,b], axis=0) : \n', np.stack([a,b], axis=0))
print('np.stack([a,b], axis=1) : \n', np.stack([a,b], axis=1))
print('np.stack([a,b], axis=2) : \n', np.stack([a,b], axis=2))
print('np.vstack([a,b]) : \n', np.vstack([a,b]))
print('np.hstack([a,b]) : \n', np.hstack([a,b]))
print('np.dstack([a,b]) : \n', np.dstack([a,a,a]))

a : 
 [[1 2 3]
 [4 5 6]]
b : 
 [[8 7 6]
 [5 4 3]]

np.concatenate([a,b]) : 
 [[1 2 3]
 [4 5 6]
 [8 7 6]
 [5 4 3]]
np.concatenate([a,b], axis=1) : 
 [[1 2 3 8 7 6]
 [4 5 6 5 4 3]]

np.stack([a,b]) : 
 [[[1 2 3]
  [4 5 6]]

 [[8 7 6]
  [5 4 3]]]
np.stack([a,b], axis=0) : 
 [[[1 2 3]
  [4 5 6]]

 [[8 7 6]
  [5 4 3]]]
np.stack([a,b], axis=1) : 
 [[[1 2 3]
  [8 7 6]]

 [[4 5 6]
  [5 4 3]]]
np.stack([a,b], axis=2) : 
 [[[1 8]
  [2 7]
  [3 6]]

 [[4 5]
  [5 4]
  [6 3]]]
np.vstack([a,b]) : 
 [[1 2 3]
 [4 5 6]
 [8 7 6]
 [5 4 3]]
np.hstack([a,b]) : 
 [[1 2 3 8 7 6]
 [4 5 6 5 4 3]]
np.dstack([a,b]) : 
 [[[1 1 1]
  [2 2 2]
  [3 3 3]]

 [[4 4 4]
  [5 5 5]
  [6 6 6]]]


# 배열 분리

* np.array_split() : 배열을 축과 인덱스를 기준으로 분리함

In [152]:
a = np.arange(16).reshape(4,4)

print('a : \n', a)
print('\n0,1행 / 2,3행 으로 쪼갬')
pprint(np.array_split(a, 2, axis=0))   # 
print('\n0,1행 / 2행 / 3행 으로 쪼갬')
pprint(np.array_split(a, (2, 3), axis=0)) # 
print('\n0,1열 / 2열 / 3열로 쪼갬')
pprint(np.array_split(a, (2, 3), axis=1)) # 

a : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

0,1행 / 2,3행 으로 쪼갬
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]

0,1행 / 2행 / 3행 으로 쪼갬
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

0,1열 / 2열 / 3열로 쪼갬
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]),
 array([[ 2],
       [ 6],
       [10],
       [14]]),
 array([[ 3],
       [ 7],
       [11],
       [15]])]


# 배열 쌓기 도우미

* .r_ : 행으로 쌓아줌

* .c_ : 열로 쌓아줌

In [156]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[2,4,6], [1,3,5]])

print('np.r_[a,b] : \n', np.r_[a,b])

print('np.c_[a,b] : \n', np.c_[a,b])

np.r_[a,b] : 
 [[1 2 3]
 [4 5 6]
 [2 4 6]
 [1 3 5]]
np.c_[a,b] : 
 [[1 2 3 2 4 6]
 [4 5 6 1 3 5]]
