In [25]:
import numpy as np

# scalar vector matrix tensor

* 0차텐서, 스칼라 : 축이 없는 값
    * ex 1, 2
* 1차텐서, 벡터 : 축을 하나 가짐
    * ex [1,2,3]
* 2차 텐서, 메트릭스, 행렬 : 축을 두개 가짐
    * ex   
    1,2,3  
    4,5,6
   
* 3차텐서, 텐서 : 축을 3개 가짐



In [26]:
a = np.array(1)

print('a.ndim : ', a.ndim)
print('a.shape : ', a.shape)
print('a.dtype : ', a.dtype)

a.ndim :  0
a.shape :  ()
a.dtype :  int64


In [27]:
a = np.array([1])

print('a.ndim : ', a.ndim)
print('a.shape : ', a.shape)
print('a.dtype : ', a.dtype)

a.ndim :  1
a.shape :  (1,)
a.dtype :  int64


# 1차원 벡터 생성

* np.arange(start, end, gap)
    * 데이터 형식을 지정하지 않으면 알아서 추론함
    * 종료(end)는 포함하지 않는다!!
    
* np.linspace(start, end, step)
    * 구간을 step수만큼 쪼갠다
    * 종료(end)를 포함한다. (endpoint=False로 제외할 수 있음)
    * retstep=True 파라미터로 증분을 표시할 수 있음

* np.logspace(start, end, step)
    * 상용로그 기준 start ~ end가 나오는 값들로 만든다
    * ex) np.logspace(0, 2, 4) 이면 log_10(x) = 0, 0.6, 1.3, 2.0이 되는 수를 만든다
        * => [1, 4.6, 21.5, 100]

In [28]:
a = np.arange(10)
b = np.arange(1, 10, 0.5)
c = np.linspace(1, 10, 10)
d = np.logspace(1, 4, 10)

print('a : ', a)
print('a.dtype : ', a.dtype)

print('b : ', b)
print('b.dtype : ', b.dtype)

print('c : ', c)
print('c.dtype : ', c.dtype)
print(np.linalg.norm(c))

print('d : ', d)
print('d.dtype : ', d.dtype)

a :  [0 1 2 3 4 5 6 7 8 9]
a.dtype :  int64
b :  [1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]
b.dtype :  float64
c :  [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
c.dtype :  float64
19.621416870348583
d :  [   10.            21.5443469     46.41588834   100.
   215.443469     464.15888336  1000.          2154.43469003
  4641.58883361 10000.        ]
d.dtype :  float64


# 벡터 크기 계산, 단위벡터

벡터의 크기(노름)는 뭐...알지??  
np.linalg.norm()으로 쉽게 구할 수 있다.  

단위벡터는 벡터를 벡터의 노름으로 나눠주면 된다.

In [29]:
a = np.arange(4)

n1 = np.sqrt(np.sum(a ** 2))
print(n1)

n2 = np.linalg.norm(a)
print(n2)

a_n = a / n1
print('a : ', a)
print('a 단위 벡터 : ',a_n)

3.7416573867739413
3.7416573867739413
a :  [0 1 2 3]
a 단위 벡터 :  [0.         0.26726124 0.53452248 0.80178373]


# 벡터의 상등과 벡터간 거리

동일한 벡터인지 확인은 np.arra_equal()을 통해 확인한다.  

또한 두 벡터간 거리라 하면 두 벡터의 차의 제곱의 합의 제곱근을 말한다
즉 


In [30]:
a = np.array([1,2,3])
b = np.array([1,2,3])
c = np.array([3,4,5])

print('a와 b의 상등 확인 : ', np.array_equal(a,b))
print('a와 b의 노름 비교 : ', np.linalg.norm(a) == np.linalg.norm(b))

print('벡터 거리 1 : ', np.sqrt(np.sum((c - a) ** 2)))
print('벡터 거리 2 : ', np.linalg.norm(c - a))

a와 b의 상등 확인 :  True
a와 b의 노름 비교 :  True
벡터 거리 1 :  3.4641016151377544
벡터 거리 2 :  3.4641016151377544


# 행렬

* np.full(shape, value, dtype)
    * shape모양으로 value를 채운다

In [31]:
a = np.array([[1], [2]])
print('2 * 1 행렬 : \n', a) 
print('a.ndim : ', a.ndim)
print('a.shape : ', a.shape)

b = np.full((3,4), 9, np.int64)
print('3 * 4 행렬 : \n', b)

2 * 1 행렬 : 
 [[1]
 [2]]
a.ndim :  2
a.shape :  (2, 1)
3 * 4 행렬 : 
 [[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


# 랭크
선형독립인 열벡터의 수  
m * n의 행렬A 가 있다면, r(A) <= min(m, n)이다.

행렬식이 0이 나온다  
=> 선형 종속이다  
=> 최소한 전부 선형독립이 아니다.  

a는 하나의 벡터이므로 무조건 선형 독립  
b는 1행과 2행이 선형 종속이기 때문에 랭크는 1  
c는 1,2,3행 모두 독립이므로 랭크는 3

In [32]:
a = np.array([1,2,3,4])
b = np.array([
    [1,2,3],
    [2,4,6]
])
c = np.array([
    [1,2,3],
    [2,2,6],
    [1,2,5]
])
print('a의 랭크 : ', np.linalg.matrix_rank(a))
print('b의 랭크 : ', np.linalg.matrix_rank(b))
print('c의 랭크 : ', np.linalg.matrix_rank(c))
print(np.linalg.det(c))



a의 랭크 :  1
b의 랭크 :  1
c의 랭크 :  3
-4.0


# 텐서와 축(axis)
텐서는 다양한 차원을 가지는 벡터와 행렬의 추상적 명칭(앞에서 다룸)   

* 1차원 텐서에서의 축에따른 계산
    * 어차피 0축만 있기 때문에 쓰나 마나 동일함.
    
* 2차원 텐서에서의 축에따른 계산
    * .sum()만 할경우 모든 원소의 합
    * .sum(axis=0)으로 할경우 0번축(열기준)으로 원소 계산

* 3차원, 4차원 텐서도 동일하다.
    * 즉 .sum()만 할경우 모든 원소의 합을 줌
    * .sum(axis=n)을 지정할 경우 해당 축을 기준으로 합을 계산.

In [33]:
a = np.arange(1, 10)
b = np.array([[1,2],[3,4]])
c = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])

print('a.sum() : ',a.sum())
print('a.sum(axis=0) : ', a.sum(axis=0))
print()

print('b.sum() : ', b.sum())
print('b.sum(axis=0) : ', b.sum(axis=0))
print('b.sum(axis=1) : ', b.sum(axis=1))
print()

print('c.sum() : ', c.sum())
print('c.sum(axis=0) : \n', c.sum(axis=0))
print('c.sum(axis=1) : \n', c.sum(axis=1))
print('c.sum(axis=2) : \n', c.sum(axis=2))
print()






a.sum() :  45
a.sum(axis=0) :  45

b.sum() :  10
b.sum(axis=0) :  [4 6]
b.sum(axis=1) :  [3 7]

c.sum() :  36
c.sum(axis=0) : 
 [[ 6  8]
 [10 12]]
c.sum(axis=1) : 
 [[ 4  6]
 [12 14]]
c.sum(axis=2) : 
 [[ 3  7]
 [11 15]]



# 축변환

a2 => transpose
0번축을 1번축으로,  
1번축을 2번축으로,  
2번축을 0번축으로 바꾼것이다.

즉 배열에서 가장 안쪽에 있던 2번축 즉 0 과 1, 2와 3 ...등이 0 번축으로 바뀌어 배열을 우선적으로 나누는데 쓰임
배열의 중간에 있던 1번축은 2번 축으로 즉 가장 안쪽으로 들어가게 되었다.  0,2,4,6  1,3,5,7 들은 가장 안쪽에 있음...

rollaxis는 각 축을 변경함.

In [34]:
a = np.arange(24)
a1 = a.reshape(3,4,2)
a2 = a1.transpose(2,0,1) 

print('3 * 4 * 2의 형태 : \n ', a1)
print('a1에서 행의 순서를 바꿈 : \n ', a2)
print()

b = np.ones((1,2,3,4))
print('b.shape : ', b.shape)
print('축 변경 : ', np.rollaxis(b, 3, 2).shape)
print()

c = np.array([[1,2,3,4,5]])
print('c : ', c)
print('c.T : \n', c.T)
print('np.swapaxes(c, 0, 1) : \n', np.swapaxes(c, 0, 1))



3 * 4 * 2의 형태 : 
  [[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
a1에서 행의 순서를 바꿈 : 
  [[[ 0  2  4  6]
  [ 8 10 12 14]
  [16 18 20 22]]

 [[ 1  3  5  7]
  [ 9 11 13 15]
  [17 19 21 23]]]

b.shape :  (1, 2, 3, 4)
축 변경 :  (1, 2, 4, 3)

c :  [[1 2 3 4 5]]
c.T : 
 [[1]
 [2]
 [3]
 [4]
 [5]]
np.swapaxes(c, 0, 1) : 
 [[1]
 [2]
 [3]
 [4]
 [5]]


# 배열 확장 및 축소

* np.expand_dims(arr, axis)
    * 지정하는 축을 추가한다.

* flatten(), ravel()
    * 앞에서 설명했으므로 생략한다.

In [35]:
a = np.array([1,2])
b = np.expand_dims(a, axis=0)
c = np.expand_dims(a, axis=1)

print(a)
print(b)
print(c)



[1 2]
[[1 2]]
[[1]
 [2]]


# 행렬의 종류들

# 정사각행렬

행과 열이 동일함.  

## 궤적 : Trace
주대각선 원소의 합  
.trace()

In [36]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print('a : ', a)

print('a.trace() : ', a.trace())

a :  [[1 2 3]
 [4 5 6]
 [7 8 9]]
a.trace() :  15


# 대각행렬
정사각행렬일때 주대각선을 제외한 모든 원소가 0임

* .diagonal() : 주대각선의 원소만 뽑아냄
* np.diag() : 1차원 배열을 받아 대각행렬을 만들어냄
    * k값을 임의로 지정하여 대각선의 위치를 지정 가능
        * 주대각선 0을 기준으로 주대각선 보다 위에있는 대각선은 양수, 아래있는 대각선은 음수다



In [37]:
a = np.array([[1,0,0], [0,3,0], [0,0,5]])

print('a : \n', a)
print('a.diagonal() : ', a.diagonal())
print('np.diag([2,4,6]) : \n', np.diag([2,4,6]))
print('np.diag([2,4,6], k = 1) : \n', np.diag([2,4,6], k = 1))

a : 
 [[1 0 0]
 [0 3 0]
 [0 0 5]]
a.diagonal() :  [1 3 5]
np.diag([2,4,6]) : 
 [[2 0 0]
 [0 4 0]
 [0 0 6]]
np.diag([2,4,6], k = 1) : 
 [[0 2 0 0]
 [0 0 4 0]
 [0 0 0 6]
 [0 0 0 0]]


# 단위행렬(항등행렬)

대각행렬중 주대각선 원소가 모두 1인 행렬.  
이 행렬에 다른 행렬을 곱하여도 동일한 행렬 반환 (곱셈의 항등원)
* np.np.eye() 단위 행렬을 만든다
    * 이또한 역시 k값을 임의로 주어 다른 위치의 대각선으로도 가능함.

* np.identity() : 항등행렬을 만든다

In [38]:
a = np.eye(3,3)
print(a)
print()

b = np.eye(3,3, k = 1)
print(b)
print()

c = np.identity(3)
d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(c)
print(c @ d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# 삼각행렬
주대각선 기준 위, 아래 값이 전부 0인경우  
* 하삼각행렬 : tril
    * np.tril() 메소드로 정사사각 행렬의 주대각선 밑 원소를 제외하고 모두 날려버림
        * k값을 통해 다른 위치의 대각선도 가능   
* 상삼각행렬 : triu
    * np.triu() 메소드로 정사각 행렬의 주대각선 위 원소를 제외하고 모두 날려버림
        * k값을 통해 다른 위치의 대각선도 가능


tril과 triu는 서로 전치관계이다

In [39]:
a = np.array(np.arange(1, 10)).reshape(3,3)
b = np.array(np.arange(10, 1, -1)).reshape(3,3)
c = np.array([1,2,3,4])

a_tril = np.tril(a)
a_tril2 = np.tril(a, k = -1)
b_triu = np.triu(b)
c = np.tril(c)
print('a_tril : \n', a_tril)
print('a_tril2 : \n ', a_tril2)
print('b_triu : \n', b_triu)
print('c : \n', c) #이런 방법도 있음

print('a_tril.T : \n' , a_tril.T)

a_tril : 
 [[1 0 0]
 [4 5 0]
 [7 8 9]]
a_tril2 : 
  [[0 0 0]
 [4 0 0]
 [7 8 0]]
b_triu : 
 [[10  9  8]
 [ 0  6  5]
 [ 0  0  2]]
c : 
 [[1 0 0 0]
 [1 2 0 0]
 [1 2 3 0]
 [1 2 3 4]]
a_tril.T : 
 [[1 4 7]
 [0 5 8]
 [0 0 9]]


# 영행렬

* np.zeros() : shape를 주어 0행렬을 만든다

* np.zeros_like() : 기존 행렬을 주어 그와 같은 shape의 행렬을 만든다

In [40]:
a = np.zeros((4,5))
b = np.zeros_like(np.array(
    [
        [1,2,3,4], 
        [5,6,7,8]
    ])
)

print('a : \n', a)
print()

print('b : \n', b)

a : 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

b : 
 [[0 0 0 0]
 [0 0 0 0]]


# 대칭행렬
주대각선 기준으로 위 아래 원소가 동일함.

# 반 대칭행렬
주대각 성분 기준 값은 같지만 부호가 반대임.

In [41]:
a = np.array([[1,2,3],[2,3,5], [3,5,6]])

print(a)
print()
print(a.T)
print()

b = np.array([[0,2,-3], [-2,0,5], [3,-5,0]])
print(b)
print()
print(b.T)
print()

[[1 2 3]
 [2 3 5]
 [3 5 6]]

[[1 2 3]
 [2 3 5]
 [3 5 6]]

[[ 0  2 -3]
 [-2  0  5]
 [ 3 -5  0]]

[[ 0 -2  3]
 [ 2  0 -5]
 [-3  5  0]]



# 치환행렬
단위행렬이나 행을 교환해 재구성 함.  
행변환을 한 단위 행렬과 행렬을 곱셈(dot product) 한다.

In [42]:
a = np.array(np.arange(1,10)).reshape(3,3)
b = np.array([[0,1,0], [1,0,0], [0,0,1]])
print(a)
print()

print(b)
print()

print(np.dot(a,b))
print()

print(a @ b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[0 1 0]
 [1 0 0]
 [0 0 1]]

[[2 1 3]
 [5 4 6]
 [8 7 9]]

[[2 1 3]
 [5 4 6]
 [8 7 9]]


# 직교행렬

자기 자신의 행렬과 전치 행렬을 행렬곱으로 계산한 결과
A @ A.T
**직교행렬의 전치행렬은 역행렬이다**
# 전치행렬

행렬의 모든 행과 열을 바꾸면 전치 행렬임.


In [43]:
a = np.array([[1,2],[3,4]])
print(a)

print(a.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
