In [11]:
import numpy as np
from pprint import pprint

# 색인검색
대괄호 사용해 원소를 조회함.

In [8]:
a = np.array(np.arange(10))

print('a : ', a)
print('a[0] : ', a[0])
print('a[-1] : ', a[-1])
print()

b = a.reshape(2,5)
print('b : \n', b)
print('b[0] : ', b[0])
print('b[0, 3] : ', b[0, 3])



a :  [0 1 2 3 4 5 6 7 8 9]
a[0] :  0
a[-1] :  9

b : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
b[0] :  [0 1 2 3 4]
b[0, 3] :  3


# 슬라이스 검색

* a:b =>  a 부터 b까지
* a: => a부터 ~ 까지
* :b => ~b까지
* ::a => 첫번째 원소부터 a의 간격만큼만
* a::b => a번째 원소부터 b의 간격만큼 뛰어서
* ... => 생략기호
    * ex) [:, :, :, :, 0] == [..., 0]

In [29]:
a = np.array(np.arange(1,10)).reshape(3,3)
b = np.array(np.arange(1,20))
c = np.array(np.arange(16)).reshape(2,2,2,2)

print('a : \n', a)
print('a[:, 2] : ', a[:, 2])
print('a[2, :] : ', a[2, :])
print()

print('b : ', b)
print('b[::2] : ', b[::2])
print('b[1::3] : ', b[1::3])
print()

print('c : \n', c)
print()
print('c[..., 1] : \n ', c[..., 1])
print()
print('c[:, :, :, 1] : \n ', c[:, :, :, 1])



a : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
a[:, 2] :  [3 6 9]
a[2, :] :  [7 8 9]

b :  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
b[::2] :  [ 1  3  5  7  9 11 13 15 17 19]
b[1::3] :  [ 2  5  8 11 14 17]

c : 
 [[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]

c[..., 1] : 
  [[[ 1  3]
  [ 5  7]]

 [[ 9 11]
  [13 15]]]

c[:, :, :, 1] : 
  [[[ 1  3]
  [ 5  7]]

 [[ 9 11]
  [13 15]]]
