In [2]:
import numpy as np

# 내적 (점곱) == ∙,  inner product, dot product

두벡터의 크기와 내각의 곱으로 구한다.  
또한 두 벡터의 내적은  

A = [a_1, a_2, ..., a_i]  
B = [b_1, b_2, ... , b_i] 일때   
A ∙ B = a_1 * b_1 + a_2 * b_2 + ... + a_i * b_i

In [3]:
a = np.array(np.arange(10, 15))
b = np.array(np.arange(4,9))
print('a : ', a)
print('b : ', b)

print('a @ b : ', a @ b)
print('np.dot(a,b) : ', np.dot(a,b))
print('np.inner(a,b) : ', np.inner(a,b))

a :  [10 11 12 13 14]
b :  [4 5 6 7 8]
a @ b :  370
np.dot(a,b) :  370
np.inner(a,b) :  370


# 외적 (가위곱) == ☓, cross product, **outer product (아래서 다룸)
외적은 두 벡터를 지나는 평면과 수직인 벡터를 구하는것이다.
```
[1,4]   
[3,6]

=> 1 * 6 - 4 * 3
```

* np.cross() : 가위곱 => 수직인 벡터

In [7]:
a = np.array([1,4])
b = np.array([3,6])
print('np.cross(a,b) : ', np.cross(a,b))
print('이렇게 보는게 맞지 모르겠지만, 두 벡터는 xyz 공간에 대해 (1,4,0), (3,6,0)인 것이고 \n외적의 결과는 (0,0,-6)과 같은것 같음')
print()

c = np.array([1,4,3])
d = np.array([3,4,5])
print('np.cross(c,d) : ', np.cross(c,d))



np.cross(a,b) :  -6
이렇게 보는게 맞지 모르겠지만, 두 벡터는 xyz 공간에 대해 (1,4,0), (3,6,0)인 것이고 
외적의 결과는 (0,0,-6)과 같은것 같음

np.cross(c,d) :  [ 8  4 -8]


# **선형대수에서 외적 : outer product


    
```
A = [a,b,c].T  
B = [d,e,f,g].T

A ☓ B = 
ad ae af ag  
bd be bf bg  
cd ce cf cg  
```
가 된다.

* np.outer() : outer product 

In [5]:
a = np.array([1,4,3])
b = np.array([3,4,5])
print('np.outer(c,d) : \n', np.outer(a, b))

np.outer(c,d) : 
 [[ 3  4  5]
 [12 16 20]
 [ 9 12 15]]
