In [1]:
import numpy as np

# 행렬

* np.full(shape, value, dtype)
    * shape모양으로 value를 채운다

In [9]:
a = np.array([[1], [2]])
print('2 * 1 행렬 : \n', a) 
print('a.ndim : ', a.ndim)
print('a.shape : ', a.shape)

b = np.full((3,4), 9, np.int64)
print('3 * 4 행렬 : \n', b)

2 * 1 행렬 : 
 [[1]
 [2]]
a.ndim :  2
a.shape :  (2, 1)
3 * 4 행렬 : 
 [[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


# 랭크
선형독립인 열벡터의 수  
m * n의 행렬A 가 있다면, r(A) <= min(m, n)이다.

행렬식이 0이 나온다  
=> 선형 종속이다  
=> 최소한 전부 선형독립이 아니다.  

a는 하나의 벡터이므로 무조건 선형 독립  
b는 1행과 2행이 선형 종속이기 때문에 랭크는 1  
c는 1,2,3행 모두 독립이므로 랭크는 3

In [21]:
a = np.array([1,2,3,4])
b = np.array([
    [1,2,3],
    [2,4,6]
])
c = np.array([
    [1,2,3],
    [2,2,6],
    [1,2,5]
])
print('a의 랭크 : ', np.linalg.matrix_rank(a))
print('b의 랭크 : ', np.linalg.matrix_rank(b))
print('c의 랭크 : ', np.linalg.matrix_rank(c))
print(np.linalg.det(c))


a의 랭크 :  1
b의 랭크 :  1
c의 랭크 :  3
-4.0


# 텐서와 축(axis)
텐서는 다양한 차원을 가지는 벡터와 행렬의 추상적 명칭(앞에서 다룸)   

* 1차원 텐서에서의 축에따른 계산
    * 어차피 0축만 있기 때문에 쓰나 마나 동일함.
    
* 2차원 텐서에서의 축에따른 계산
    * .sum()만 할경우 모든 원소의 합
    * .sum(axis=0)으로 할경우 0번축(열기준)으로 원소 계산

* 3차원, 4차원 텐서도 동일하다.
    * 즉 .sum()만 할경우 모든 원소의 합을 줌
    * .sum(axis=n)을 지정할 경우 해당 축을 기준으로 합을 계산.

In [29]:
a = np.arange(1, 10)
b = np.array([[1,2],[3,4]])
c = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])

print('a.sum() : ',a.sum())
print('a.sum(axis=0) : ', a.sum(axis=0))
print()

print('b.sum() : ', b.sum())
print('b.sum(axis=0) : ', b.sum(axis=0))
print('b.sum(axis=1) : ', b.sum(axis=1))
print()

print('c.sum() : ', c.sum())
print('c.sum(axis=0) : \n', c.sum(axis=0))
print('c.sum(axis=1) : \n', c.sum(axis=1))
print('c.sum(axis=2) : \n', c.sum(axis=2))
print()





a.sum() :  45
a.sum(axis=0) :  45

b.sum() :  10
b.sum(axis=0) :  [4 6]
b.sum(axis=1) :  [3 7]

c.sum() :  36
c.sum(axis=0) : 
 [[ 6  8]
 [10 12]]
c.sum(axis=1) : 
 [[ 4  6]
 [12 14]]
c.sum(axis=2) : 
 [[ 3  7]
 [11 15]]



# 축변환

a2 => transpose
0번축을 1번축으로,  
1번축을 2번축으로,  
2번축을 0번축으로 바꾼것이다.

즉 배열에서 가장 안쪽에 있던 2번축 즉 0 과 1, 2와 3 ...등이 0 번축으로 바뀌어 배열을 우선적으로 나누는데 쓰임
배열의 중간에 있던 1번축은 2번 축으로 즉 가장 안쪽으로 들어가게 되었다.  0,2,4,6  1,3,5,7 들은 가장 안쪽에 있음...

rollaxis는 각 축을 변경함.

In [44]:
a = np.arange(24)
a1 = a.reshape(3,4,2)
a2 = a1.transpose(2,0,1) 

print('3 * 4 * 2의 형태 : \n ', a1)
print('a1에서 행의 순서를 바꿈 : \n ', a2)
print()

b = np.ones((1,2,3,4))
print('b.shape : ', b.shape)
print('축 변경 : ', np.rollaxis(b, 3, 2).shape)
print()

c = np.array([[1,2,3,4,5]])
print('c : ', c)
print('c.T : \n', c.T)
print('np.swapaxes(c, 0, 1) : \n', np.swapaxes(c, 0, 1))


3 * 4 * 2의 형태 : 
  [[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
a1에서 행의 순서를 바꿈 : 
  [[[ 0  2  4  6]
  [ 8 10 12 14]
  [16 18 20 22]]

 [[ 1  3  5  7]
  [ 9 11 13 15]
  [17 19 21 23]]]

b.shape :  (1, 2, 3, 4)
축 변경 :  (1, 2, 4, 3)

c :  [[1 2 3 4 5]]
c.T : 
 [[1]
 [2]
 [3]
 [4]
 [5]]
np.swapaxes(c, 0, 1) : 
 [[1]
 [2]
 [3]
 [4]
 [5]]


# 배열 확장 및 축소

* np.expand_dims(arr, axis)
    * 지정하는 축을 추가한다.

* flatten(), ravel()
    * 앞에서 설명했으므로 생략한다.

In [45]:
a = np.array([1,2])
b = np.expand_dims(a, axis=0)
c = np.expand_dims(a, axis=1)

print(a)
print(b)
print(c)


[1 2]
[[1 2]]
[[1]
 [2]]
