In [14]:
import numpy as np
from pprint import pprint

# 정렬함수

* np.sort() : 정렬된 배열을 리턴한다.
* .sort() : 배열 자체를 정렬함 리턴값은 없음
* np.argsort() : 각 원소들을 정렬시 가지게될 인덱스로 리턴

## 행렬 및 배열에서 특정 행 또는 열을 통한 전체 배열 정렬
1. 행렬의 특정 행 또는 열을 추출한다 
    ex) a[:, 2] => 행렬의 2열 추출
2. 해당 추출배열에서 .argsort()를 통해 정렬된 인덱스를 얻는다
    ex) a[:, 2].argsort()
3. 팬시 검색을 통해 배열을 정렬한다
    ex) a[a[:, 2].argsort()]

In [32]:
a = np.random.randint(1,10, (2,4))

print('a : \n', a)

b = np.sort(a)
print('b : \n', b)

a.sort()
print('a : \n', a)

a = np.random.randint(1,10, (2,4))
print(a)
c = np.argsort(a)
print(c)


a = np.random.randint(1,10, (4,4))

print('a : \n', a)
print('a sorted by colum 2 : \n', a[a[:, 2].argsort()])

a : 
 [[5 7 2 8]
 [3 2 3 2]]
b : 
 [[2 5 7 8]
 [2 2 3 3]]
a : 
 [[2 5 7 8]
 [2 2 3 3]]
[[3 9 8 2]
 [7 9 1 1]]
[[3 0 2 1]
 [2 3 0 1]]
a : 
 [[3 1 9 5]
 [8 4 6 5]
 [5 1 9 8]
 [8 3 5 7]]
a sorted by colum 2 : 
 [[8 3 5 7]
 [8 4 6 5]
 [3 1 9 5]
 [5 1 9 8]]


# 배열과 메트릭스 변환

* np.asarray() : 배열로 만든다
* np.asmatrix() : 매트릭스로 만든다

In [17]:
a = np.matrix([1,2,3,4])
pprint(a)

b = np.asarray(a)
pprint(b)

c = np.asmatrix(b)
pprint(c)

matrix([[1, 2, 3, 4]])
array([[1, 2, 3, 4]])
matrix([[1, 2, 3, 4]])


# 배열 값 변경 

* .fill() : 배열의 원소의 값들을 전부 변경시킴


In [19]:
a = np.ones(4)
print('a : ', a)

a.fill(99)
print('a : ', a)

a :  [1. 1. 1. 1.]
a :  [99. 99. 99. 99.]


# 배열 원소 회전

* np.rot90() : 원소를 90도로 회전
    * 배열 이후 넣는 파라미터를 통해 180, 270..등 변환이 가능
        * n * 90 만큼 변환됨
        
* roll() : 배열을 회전시킨다 (원형 리스트와 같은 느낌)
    * ##행렬일때##
    * default : 각 원소를 평면으로 두고 이동
    * axis = 0 : 행단위로 이동
    * axis = 1 : 열단위로 이동

In [47]:
a = np.array([[1,2], [3,4]])

print('a : \n', a)
print('a rot 90: \n', np.rot90(a))
print('a rot 180 : \n', np.rot90(a, 2))
print('a rot 270 : \n', np.rot90(a, 3))
print('a rot 360 : \n', np.rot90(a, 4))
print()

a = np.arange(16).reshape(4,4)
print('a : \n', a)
print('원소별 이동 : \n', np.roll(a, 1))
print('행단위 이동 : \n', np.roll(a, 1, axis=0))
print('열단위 이동 : \n', np.roll(a, 1, axis=1))

a : 
 [[1 2]
 [3 4]]
a rot 90: 
 [[2 4]
 [1 3]]
a rot 180 : 
 [[4 3]
 [2 1]]
a rot 270 : 
 [[3 1]
 [4 2]]
a rot 360 : 
 [[1 2]
 [3 4]]

a : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
원소별 이동 : 
 [[15  0  1  2]
 [ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
행단위 이동 : 
 [[12 13 14 15]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
열단위 이동 : 
 [[ 3  0  1  2]
 [ 7  4  5  6]
 [11  8  9 10]
 [15 12 13 14]]


# 원소 점검

* np.isreal() : 전부 실수인지
* np.isinf() : 무한대 값이 있는지
* np.isnan() : Nan 값이 있는지
* np.iscomplex() : 복소수인지

* np.nonzero() : 0이 아닌값의 위치를 행행렬, 열행렬을 통해 리턴
    * 행렬의 경우 리턴되는 두개의 행렬중 첫번째는 행에 대한 정보, 두번째는 열에대한 정보다.

In [50]:
a = np.arange(16).reshape(4,4)

print('isinf : \n', np.isinf(a))
print(np.nonzero(a))

isinf : 
 [[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]
(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]), array([1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))
