In [1]:
import numpy as np

# 행렬식, 역행렬

## 행렬식
```
a b
c d
행렬식 : ad - bc

a b c
d e f
g h i
행렬식 : a(ei - hf) - b(di - gf) + c(dh - eg)
```
정사각 행렬일때 원소들을 대응해 값을 구하는 방식.  

* np.linalg.det() 행렬식을 구해준다

## 역행렬
역행렬과 원행렬을 곱하면 단위행렬이 나온다.  
원행렬의 행렬식이 0이면 구할 수 없다.

### 소행렬
M_ij = 원행렬에서 i행, j열을 제외한 행렬
```
1 2 3
4 5 6
7 8 9 
에서 M_12 = 1 2
           7 8
```

### 여인수
C_ij = (-1)^(i+j) * det(M_ij)
소행렬의 행렬식과 일정한 부호를 붙임

### 수반행렬
여인수들의 행렬의 전치행렬
즉
여인수 행렬이 다음과 같이 존재하고
```
C_11 C_12 C13
C_21 C_22 C_23
C_31 C_32 C_33
```

수반행렬은 다음과 같음.
```
C_11 C_21 C_31
C_12 C_22 C_32
C_13 C_23 C_33
```

* np.linalg.inv()
(AB)^-1 = B^-1 @ A^-1 인 특징이 있음



In [14]:
a = np.array([[1,2,3], [1,5,6], [8,8,9]])
b = np.array([[5,8,1], [2,9,7], [2,9,4]])
print("a의 행렬식 : ", np.linalg.det(a))
print("a의 역행렬 : \n ", np.linalg.inv(a))
print("aa^-1 : \n", np.linalg.inv(a) @ a)
print()
print('np.linalg.inv((a @ b)) : \n', np.linalg.inv((a @ b)))
print()
print('np.linalg.inv(b) @ np.linalg.inv(a) : \n', np.linalg.inv(b) @ np.linalg.inv(a))
print()

a의 행렬식 :  -20.99999999999999
a의 역행렬 : 
  [[ 0.14285714 -0.28571429  0.14285714]
 [-1.85714286  0.71428571  0.14285714]
 [ 1.52380952 -0.38095238 -0.14285714]]
aa^-1 : 
 [[ 1.00000000e+00  2.22044605e-16  5.55111512e-17]
 [ 0.00000000e+00  1.00000000e+00 -3.88578059e-16]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]

np.linalg.inv((a @ b)) : 
 [[-1.26984127  0.30596606  0.1592775 ]
 [ 0.95238095 -0.272578   -0.09359606]
 [-1.12698413  0.36507937  0.0952381 ]]

np.linalg.inv(b) @ np.linalg.inv(a) : 
 [[-1.26984127  0.30596606  0.1592775 ]
 [ 0.95238095 -0.272578   -0.09359606]
 [-1.12698413  0.36507937  0.0952381 ]]



# 