In [2]:
import numpy as np

# 레퍼런스
아래와 같은 방법으로 변수를 선언하면 b와 a는 같은 레퍼런스를 참조하게 되며  

b가 변화시 a도 같이 변하게 됨.

In [3]:
#cell 1
a = np.array([1,2,3,4])
b = a
b[0] = 10
print('a : ', a)
print('b : ', b)

a :  [10  2  3  4]
b :  [10  2  3  4]


# 카피
a와 값만 동일한 ndarray를 만들려면 아래와 같이 np.array()로 새로운 ndarray를 만들거나 .copy()를 이용하면 된다.

In [4]:
a = np.array([1,2,3,4])
c = np.array(a)
c[0] = 10
print('a : ', a)
print('c : ', c)

a :  [1 2 3 4]
c :  [10  2  3  4]


# dtype
기본 타입은 추론하여 지정하지만, 특별하게 dtype을 지정해 줄 수 있다.  

아래는 1,2,3,4의 기본 dtype은 int64지만 float64로 따로 지정해준 모습

In [6]:
a = np.array([1,2,3,4])
print('a.dtype 1): ', a.dtype)

a = np.array([1,2,3,4], dtype="float")
print('a.dtype 2): ', a.dtype)

a.dtype 1):  int64
a.dtype 2):  float64


# property
* .shape : 축의 원소 개수 
* .ndim : 축의 개수

2 * 3 배열인 a는 (2,3)의 shape와 2개의 축을 가짐

In [7]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[[1],[2],[3]], [[4],[5],[6]]])
print('a.shape : ', a.shape)
print('a.ndim : ', a.ndim)
print('b.shape : ', b.shape)
print('b.ndim : ', b.ndim)

a.shape :  (2, 3)
a.ndim :  2
b.shape :  (2, 3, 1)
b.ndim :  3


# property
* .dtype : 데이터타입
* .itemsize : 원소의 크기(바이트)
* .size : 데이터의 크기 (원소 개수)
* .strides : 행의 크기 [,행의 행의크기], ... ,  마지막 행의 원소크기
   
=> 2 * 2 인 경우 행은 2 * 1 이다.  
하지만 2 * 2 * 2 인 경우 최초의 행'은 2 * 2 의 형태고  
이 행'의 행''은 2 * 1의 형태다.  
즉 재귀적으로 행의 크기를 타고 들어가는 느낌..  


In [8]:
a = np.array([[1,2], [4,6]])
b = np.array([[[1,2], [3,4]], [[5,6],[7,8]]])

print('a.dtype : ', a.dtype)
print('a.itemsize : ', a.itemsize)
print('a.size : ', a.size)
print('a.strides : ', a.strides)
print('b.strides : ', b.strides)

a.dtype :  int64
a.itemsize :  8
a.size :  4
a.strides :  (16, 8)
b.strides :  (32, 16, 8)


# property
* .__array_interface__ : 해당 ndarray의 정보를 전부 출력함.
* .data : 데이터가 저장된 메모리주소
* .data.tobytes() : 데이터를 바이트로 바꿨을때 크기
* .data.hex() : 16진수로 바꿨을때
* .tolist() : ndarray => list로
* .flags : 배열의 정보 (C또는 포트란에서 표시할 수 있는지에 대해)

In [9]:
a = np.array([[1,2,3], [4,5,6]])
print('a.array_interface__ : ', a.__array_interface__)
print('a.data : ', a.data)
print('a.data.tobytes() : ', a.data.tobytes())
print('a.data.hex() : ', a.data.hex())
print('a.tolist() : ', a.tolist())
print('a.flags : ', a.flags)

a.array_interface__ :  {'data': (105553152724064, False), 'strides': None, 'descr': [('', '<i8')], 'typestr': '<i8', 'shape': (2, 3), 'version': 3}
a.data :  <memory at 0x7fcc75fdc2b0>
a.data.tobytes() :  b'\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00'
a.data.hex() :  010000000000000002000000000000000300000000000000040000000000000005000000000000000600000000000000
a.tolist() :  [[1, 2, 3], [4, 5, 6]]
a.flags :    C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



# 차원 축소
1차원으로 만드는 방법.  
* .flatten : 원본과 동일한 복사본을 1차원으로 만든다
* .ravel : 원본의 1차원 뷰를 만든다(원본도 같이 변경됨)

In [10]:
a = np.array([[1,2,3], [4,5,6]])
b = a.flatten()
c = a.ravel()

b[3] = 9
print('a : ', a)
print('b : ', b)

a = np.array([[1,2,3], [4,5,6]])
c[3] = 99
print('a : ', a)
print('c : ', c)


a :  [[1 2 3]
 [4 5 6]]
b :  [1 2 3 9 5 6]
a :  [[1 2 3]
 [4 5 6]]
c :  [ 1  2  3 99  5  6]


# 원소 접근

In [12]:
a = np.array([[1,2,3], [4,5,6]])
print('a[0][1] : ', a[0][1])
print('a[0,1] : ', a[0,1])
print('a[(0,1)] : ', a[(0,1)])

a[0][1] :  2
a[0,1] :  2
a[(0,1)] :  2


# array, matrix
array는 차원 표기시 5, 로 표기되지만,  
matrix는 무조건 행렬을 가진 (1,5)로 표기됨

또한 * 연산시 array는 각 원소가 element wise한 연산을 진행하지만  
matrix는 * 연산을 사용시 오류가 난다. => 같은 결과를 얻으려면 multiply()를 사용

In [13]:
a = np.array([1,2,3,4,5])
b = np.matrix([1,2,3,4,5])

print('a.shape : ', a.shape)
print('b.shape : ', b.shape)

c = np.asmatrix(a)
print('c : ', c)
print('c.shape : ', c.shape)

print('a * a :', a * a)
#b * b 예외
print('np.multiply(b, b) : ', np.multiply(b, b))

a.shape :  (5,)
b.shape :  (1, 5)
c :  [[1 2 3 4 5]]
c.shape :  (1, 5)
a * a : [ 1  4  9 16 25]
np.multiply(b, b) :  [[ 1  4  9 16 25]]


#  matrix의 property
* .H : 전치행렬
* .T : 전치행렬
* .I : 역행렬

In [14]:
a = np.matrix([[1,2,3], [4,5,6]])

print('a : ', a)
print()
print('a.H : ', a.H)
print()
print('a.T : ', a.T)
print()
print('a.I : ', a.I)

a :  [[1 2 3]
 [4 5 6]]

a.H :  [[1 4]
 [2 5]
 [3 6]]

a.T :  [[1 4]
 [2 5]
 [3 6]]

a.I :  [[-0.94444444  0.44444444]
 [-0.11111111  0.11111111]
 [ 0.72222222 -0.22222222]]
