In [9]:
import numpy as np
from pprint import pprint

# 메소드
* .item() : 하나의 원소를 조회한다. 만약 다차원 배열이여도 하나의 인덱스로 조회 가능함.

* .itemset() : item()과 동일한 조회방식을 사용하고, 해당 원소의 값을 재설정한다

* .take() : 배열의 인덱스를 조회하여 가져온다.

* .put() : 동일한 방식으로 조회된 인덱스에 값을 넣는다.

In [35]:
a = np.array(np.arange(20,40)).reshape(4,5)

print('a.item(14) : ',a.item(14))
print('a.item(2,2) : ',a.item(2,2))

a.itemset(14, 99)
a.itemset((2,2), 999)
print('a :')
pprint(a)

pos1 = [6,8]
pos2 = [[18, 13], [5,1]]
pos3 = [[5,1], [18, 13]]
print('a.take(pos1) # [6,8] : ', a.take(pos1))
print('a.take(pos2) # [[18, 13], [5,1]] : \n', a.take(pos2))
print('a.take(pos3) # [[5,1], [18, 13]] : \n', a.take(pos3))
print()

a.put(pos1, 9)
a.put(pos2, 0)
print('a :')
pprint(a)

a.item(14) :  34
a.item(2,2) :  32
a :
array([[ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31, 999,  33,  99],
       [ 35,  36,  37,  38,  39]])
a.take(pos1) # [6,8] :  [26 28]
a.take(pos2) # [[18, 13], [5,1]] : 
 [[38 33]
 [25 21]]
a.take(pos3) # [[5,1], [18, 13]] : 
 [[25 21]
 [38 33]]

a :
array([[ 20,   0,  22,  23,  24],
       [  0,   9,  27,   9,  29],
       [ 30,  31, 999,   0,  99],
       [ 35,  36,  37,   0,  39]])


# 질의함수

* np.choose() : 특정 인덱스를 검색
    * parameter : (i, arr) => 해당 배열의 i행 리턴
        * i는 리스트 형태도 가능
    * parameter : (tuple(list()), arr) => 복잡함.
        * ex) (tuple([0,1,2]), arr) => arr 배열의 0열0행, 1열1행, 2열2행 리턴
        * ex) (tuple([1,2,0]), arr) => arr 배열의 0열1행, 1열2행, 2열0행 리턴
        * ex) (tuple([[1], [0], [2]]), arr) => arr 배열의 1행, 0행, 2행 리턴
        
* np.where() : 조건에 해당하는 원소의 인덱스 리턴
    * 튜플 형태로 ([0번째 축 인덱스 리스트], [1번째 축 인덱스 리스트], ...) 로 리턴
        * ex) ([1,2,3], [4,5,6])  => (1행, 4열), (2행 5열), (3행 6열)

* np.select() : (잘 모르겠음)
    
* np.extract() : where로 인덱스를 구한다음 해당 인덱스의 값을 리턴한 결과임.   # 잘 모르겠음. (추가)
    * 즉 인덱스 추출 + 인덱스 원소 리턴

In [85]:
a = np.array(np.arange(20)).reshape(4,5)
print('a :')
pprint(a)
print()

print('np.choose(2, a) : ', np.choose(2, a))
print('np.choose([3], a) : ', np.choose([3], a))
print('np.choose(tuple([[1], [0], [2]]), a) : \n', np.choose(tuple([[1], [0], [2]]), a))
print()

print('np.where(a % 3 == 0) : ', np.where(a % 3 == 0))
print('a[np.where(a % 3 == 0)] : ', a[np.where(a % 3 == 0)])
print()

print('np.extract(a > 8, a) : ', np.extract(a > 8, a))
# print(a)
# print(a > 8)

# print(np.select([a > 8], [a**2]))


a :
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

np.choose(2, a) :  [10 11 12 13 14]
np.choose([3], a) :  [15 16 17 18 19]
np.choose(tuple([[1], [0], [2]]), a) : 
 [[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]]

np.where(a % 3 == 0) :  (array([0, 0, 1, 1, 2, 3, 3]), array([0, 3, 1, 4, 2, 0, 3]))
a[np.where(a % 3 == 0)] :  [ 0  3  6  9 12 15 18]

np.extract(a > 8, a) :  [ 9 10 11 12 13 14 15 16 17 18 19]
