In [2]:
import numpy as np

# 텐서곱 


np.tensordot(a,b, axes = n)

(2 * 2), (2 * 2)의 텐서곱 기준

* axes = 0 : a행렬에서의 각 원소와 b배열과의 스칼라곱을 함. 즉 a배열의 각 원소들이 b배열과의 스칼라 곱이 됨

* axes = 1 : a행렬의 각 행과 b 행렬의열의 곱셈 (행렬 곱)

* axes = 2 : a행렬의 각 원소와 b행렬의 각 원소의 곱셈의 합

In [21]:
a = np.array([[1,2], [3,4]])
b = np.array([[1,1], [1,1]])

print('axes = 0  : \n', np.tensordot(a,b, axes = 0))
print('axes = 1 : \n', np.tensordot(a,b,axes=1))
print('a @ b : \n', a @ b)
print('axes = 2 : \n', np.tensordot(a,b, axes=2))


axes = 0  : 
 [[[[1 1]
   [1 1]]

  [[2 2]
   [2 2]]]


 [[[3 3]
   [3 3]]

  [[4 4]
   [4 4]]]]
axes = 1 : 
 [[3 3]
 [7 7]]
a @ b : 
 [[3 3]
 [7 7]]
axes = 2 : 
 10


# kron연산
kronecker 크로네커곱