In [2]:
import numpy as np

# 텐서곱 


np.tensordot(a,b, axes = n)

(2 * 2), (2 * 2)의 텐서곱 기준

* axes = 0 : a행렬에서의 각 원소와 b배열과의 스칼라곱을 함. 즉 a배열의 각 원소들이 b배열과의 스칼라 곱이 됨

* axes = 1 : a행렬의 각 행과 b 행렬의열의 곱셈 (행렬 곱)

* axes = 2 : a행렬의 각 원소와 b행렬의 각 원소의 곱셈의 합

In [21]:
a = np.array([[1,2], [3,4]])
b = np.array([[1,1], [1,1]])

print('axes = 0  : \n', np.tensordot(a,b, axes = 0))
print('axes = 1 : \n', np.tensordot(a,b,axes=1))
print('a @ b : \n', a @ b)
print('axes = 2 : \n', np.tensordot(a,b, axes=2))


axes = 0  : 
 [[[[1 1]
   [1 1]]

  [[2 2]
   [2 2]]]


 [[[3 3]
   [3 3]]

  [[4 4]
   [4 4]]]]
axes = 1 : 
 [[3 3]
 [7 7]]
a @ b : 
 [[3 3]
 [7 7]]
axes = 2 : 
 10


# kron 연산
kronecker 크로네커곱

A와 B 의 크로네커 곱 결과는

```
a_11 * B | a_12 * B | ... | a_1n * B
...
a_m1 * B | a_m2 * B | ... | a_mn * B
```
즉 m * n 행렬과 a * b 행렬의 크로네커 곱 결과는 ma * nb이다.


In [9]:
a = np.array([1,2,3])
b = np.array([4,5,6])

c = np.array(
    [
        [0,1], 
        [1,0]
    ]
)
d = np.array(np.arange(9)).reshape(3,3)

print("kron a, b : ", np.kron(a,b))
print('kron c, d : \n', np.kron(c,d))

kron a, b :  [ 4  5  6  8 10 12 12 15 18]
kron c, d : 
 [[0 0 0 0 1 2]
 [0 0 0 3 4 5]
 [0 0 0 6 7 8]
 [0 1 2 0 0 0]
 [3 4 5 0 0 0]
 [6 7 8 0 0 0]]


# einsum 합 (나중에)