In [2]:
import numpy as np

# 행렬곱 dot product == @, .dot(), np.dot()
흔히 아는 행렬의 곱셈이다.

A = (m , p)  
B = (p , n)  
일때 A ∙ B 의 결과는 (m , n)이다.  

```
A = [[1,2],
     [3,4]]
     
B = [[5,6,7],
     [8,9,0]]
     
A ∙ B = 
1*5 + 2*8 | 1*6 + 2*9 | 1*7 + 2*0
3*5 + 3*8 | 3*6 + 3*9 | 3*7 + 3*0

```
     
## vdot 
행렬의 모든 원소를 1차원 벡터로 변환하여 내적을 구한다

In [3]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6,7], [8,9,0]])

print('a @ b : \n', a @ b)
print('a.dot(b) : \n', a.dot(b))
print('np.dot(a,b) : \n', np.dot(a,b))

a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
c = np.array([1,2,3,4])
d = np.array([5,6,7,8])


print('np.vdot(a,b) : ', np.vdot(a,b))
print('c @ d : ', c @ d)

a @ b : 
 [[21 24  7]
 [47 54 21]]
a.dot(b) : 
 [[21 24  7]
 [47 54 21]]
np.dot(a,b) : 
 [[21 24  7]
 [47 54 21]]
np.vdot(a,b) :  70
c @ d :  70


# 행렬 연산

## inner
행렬 A, B의 inner연산은 dot연산과 동일하다.

## outer
행렬의 outer연산은 행렬을 벡터로 만들어 이 벡터를 outer product한 것이다

## cross 
행울 기준으로 벡터간 cross연산을 함.

In [4]:
a = np.array([[1,2], [3,4]])

b = np.array([[3,2], [3,4]])

# print(np.inner(a,b))
print('a @ b : \n', a @ b)
print()
print('np.dot(a,b) : \n', np.dot(a,b))
print()
print('np.outer(a,b) : \n',np.outer(a,b))
print()

print(np.cross(a,b))

a @ b : 
 [[ 9 10]
 [21 22]]

np.dot(a,b) : 
 [[ 9 10]
 [21 22]]

np.outer(a,b) : 
 [[ 3  2  3  4]
 [ 6  4  6  8]
 [ 9  6  9 12]
 [12  8 12 16]]

[-4  0]


# 텐서곱 


np.tensordot(a,b, axes = n)

(2 * 2), (2 * 2)의 텐서곱 기준

* axes = 0 : a행렬에서의 각 원소와 b배열과의 스칼라곱을 함. 즉 a배열의 각 원소들이 b배열과의 스칼라 곱이 됨

* axes = 1 : a행렬의 각 행과 b 행렬의열의 곱셈 (행렬 곱)

* axes = 2 : a행렬의 각 원소와 b행렬의 각 원소의 곱셈의 합

In [ ]:
a = np.array([[1,2], [3,4]])
b = np.array([[1,1], [1,1]])

print('axes = 0  : \n', np.tensordot(a,b, axes = 0))
print('axes = 1 : \n', np.tensordot(a,b,axes=1))
print('a @ b : \n', a @ b)
print('axes = 2 : \n', np.tensordot(a,b, axes=2))



# kron연산
kronecker 크로네커곱