In [2]:
import numpy as np

# ndarray클래스와 numpy 모듈
ndarray클래스에 있는 메소드들과 numpy 모듈에 있는 메소드들중 겹치는 메소드들이 있다.  

약 47개정도 있음.  any, all은 그중 하나다.  

**이들은 사용방법은 다르지만 동일한 결과를 가짐**
 
* .any() : 그중 하나라도 True가 있으면 True
* .all() : 그중 모든 원소가 True이면 True

In [3]:
a = np.zeros((4,4))
print('a != 0 : ', a != 0)
print('np.any(a == 0) : ', np.any(a == 0))
print('(a == 0).any() : ', (a == 0).any())

a != 0 :  [[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]
np.any(a == 0) :  True
(a == 0).any() :  True


# 벡터화 연산

순환하며 차례로 연산하는 것이 아닌 인덱스끼리 연산을 자동으로 처리하는것을 벡터화 연산이라 한다.  
universal함수(ufunc)는 벡터화 연산을 할 수 있는 기능 제공함  
* `*` 연산은 ufunc로 인덱스 원소끼리 곱한다.
* np.newaxis 는 새로운 차원 축을 추가한다.  
    * np.newaxis를 추가하는 위치에 따라 결과가 달라짐
        * np.newaxis는 None다!?
        * np.newaxis대신 None을 사용하여도 같은 결과가 나오는거 같음!
* @는 dot product를 실행함

In [4]:
a = np.arange(6, 10)
b = np.arange(10, 14)

c = a * b

d = a[:,None]
e = a[np.newaxis, :]


print('a.shape : ', a.shape)
print('d.shape : ', d.shape)
print('e.shape : ', e.shape)

print('d @ e : ', d @ e)

a.shape :  (4,)
d.shape :  (4, 1)
e.shape :  (1, 4)
d @ e :  [[36 42 48 54]
 [42 49 56 63]
 [48 56 64 72]
 [54 63 72 81]]


# 축 계산

* .reshape : 축변환

## 지정된 축에서의 연산

메소드에 axis 파라미터값으로 축을 주지 않으면 해당 배열의 모든 값으로 연산을 진행하지만,  
axis를 파라미터로 넘겨주면 해당 축을 기준으로 연산을 수행함


In [5]:
a = np.array([1,2,3,4])
b = a.reshape(2,2)
print('b : ', b)

print('b.sum() : ', b.sum())
print('b.sum(axis=1) : ', b.sum(axis=1))

b :  [[1 2]
 [3 4]]
b.sum() :  10
b.sum(axis=1) :  [3 7]


# 원소 개수 일치 (차원 유지)
벡터간 연산을 하려면 동일한 차원을 가져야함.  
ex) 4차원 벡터와 원소 연산(element wise)을 할려면 동일한 4차원 벡터 필요

## 브로드 캐스팅
하지만 일정한 조건이 맞는다면 동일한 차원이 아니여도 가능함.  
가장 쉬운 예시가 벡터와, 스칼라의 원소 연산
https://sacko.tistory.com/16 참조


In [6]:
a = np.array([1,2,3,4])
b = np.array([1,2,3])

print(a + b)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 