In [1]:
import numpy as np

### [1. 행렬곱](#행렬곱)
### [2. 행렬연산](#행렬연산)
### [3. 텐서곱](#텐서곱)
### [4. axis에 대하여](#axis에대하여)

# 행렬곱 
## dot product == @, .dot(), np.dot()
흔히 아는 행렬의 곱셈이다.

A = (m , p)  
B = (p , n)  
일때 A ∙ B 의 결과는 (m , n)이다.  

```
A = [[1,2],
     [3,4]]
     
B = [[5,6,7],
     [8,9,0]]
     
A ∙ B = 
1*5 + 2*8 | 1*6 + 2*9 | 1*7 + 2*0
3*5 + 3*8 | 3*6 + 3*9 | 3*7 + 3*0

```
     
## vdot 
행렬의 모든 원소를 1차원 벡터로 변환하여 내적을 구한다

In [2]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6,7], [8,9,0]])

print('a @ b : \n', a @ b)
print('a.dot(b) : \n', a.dot(b))
print('np.dot(a,b) : \n', np.dot(a,b))

a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
c = np.array([1,2,3,4])
d = np.array([5,6,7,8])


print('np.vdot(a,b) : ', np.vdot(a,b))
print('c @ d : ', c @ d)

a @ b : 
 [[21 24  7]
 [47 54 21]]
a.dot(b) : 
 [[21 24  7]
 [47 54 21]]
np.dot(a,b) : 
 [[21 24  7]
 [47 54 21]]
np.vdot(a,b) :  70
c @ d :  70


# 행렬연산

## inner
행렬 A, B의 inner연산은 dot연산과 동일하다.

## outer
행렬의 outer연산은 행렬을 벡터로 만들어 이 벡터를 outer product한 것이다

## cross 
행울 기준으로 벡터간 cross연산을 함.

In [3]:
a = np.array([[1,2], [3,4]])

b = np.array([[3,2], [3,4]])

# print(np.inner(a,b))
print('a @ b : \n', a @ b)
print()
print('np.dot(a,b) : \n', np.dot(a,b))
print()
print('np.outer(a,b) : \n',np.outer(a,b))
print()

print(np.cross(a,b))

a @ b : 
 [[ 9 10]
 [21 22]]

np.dot(a,b) : 
 [[ 9 10]
 [21 22]]

np.outer(a,b) : 
 [[ 3  2  3  4]
 [ 6  4  6  8]
 [ 9  6  9 12]
 [12  8 12 16]]

[-4  0]


# 텐서곱 


np.tensordot(a,b, axes = n)

(2 * 2), (2 * 2)의 텐서곱 기준

* axes = 0 : a행렬에서의 각 원소와 b배열과의 스칼라곱을 함. 즉 a배열의 각 원소들이 b배열과의 스칼라 곱이 됨

* axes = 1 : a행렬의 각 행과 b 행렬의열의 곱셈 (행렬 곱)

* axes = 2 : a행렬의 각 원소와 b행렬의 각 원소의 곱셈의 합

In [4]:
a = np.array([[1,2], [3,4]])
b = np.array([[1,1], [1,1]])

print('axes = 0  : \n', np.tensordot(a,b, axes = 0))
print('axes = 1 : \n', np.tensordot(a,b,axes=1))
print('a @ b : \n', a @ b)
print('axes = 2 : \n', np.tensordot(a,b, axes=2))



axes = 0  : 
 [[[[1 1]
   [1 1]]

  [[2 2]
   [2 2]]]


 [[[3 3]
   [3 3]]

  [[4 4]
   [4 4]]]]
axes = 1 : 
 [[3 3]
 [7 7]]
a @ b : 
 [[3 3]
 [7 7]]
axes = 2 : 
 10


# axis에대하여

연산에 자주 사용되는 axis(축) 에 대해 설명한다.  
축은 연산의 기준을 정하게 된다. 
그리고 대게 다음과 같은 규칙을 따르니 어느정도 숙지를 하면 좋다. 
* 축을 지정하지 않는다면(default) 배열 자체에 대한 연산이라 본다
* 축은 작을수록 큰 차원에서 계산된다.  
ex)
```
[                    #1
    [                #2
        [1,2],       #3
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
]
```
다음과 같은 3차원 배열이라면  
axis를 지정하지 않는다면 전체 배열 **#1**을 보고 계산한다.  
        즉 1,2,3,4,5,6,7,8중 가장 큰 8 리턴
axis=0 이라면 배열중 가장 외각 차원? 가장 큰 차원?인 **#2** 수준에서 계산된다.  
        즉 [[1,2],[3,4]] 와 [[5,6],[7,8]]을 비교해 후자가 더 크므로 후자를 리턴한다.
axis=1 이라면 그다음 수준인 **#3** 수준에서 계산된다.
        즉 [1,2], [3,4]중 더 큰 [3,4] 그리고 [5,6]과 [7,8] 중 더 큰 [7,8] 이 리턴되어 [[3,4], [7,8]]이 리턴된다.
axis=2 이라면 그다음 수준인 원소 수준에서 비교된다.
        즉 [1,2] 중 2 / [3,4]중 4 / [5,6] 중 6 / [7,8] 중 8 이 리턴되어 [[2,4], [6,8]]이 리턴됨.

In [5]:
a = np.arange(1,9).reshape(2,2,2)
print(a)
print()
print('np.max(a) : \n', np.max(a))
print('np.max(a, axis=0) : \n', np.max(a, axis=0))
print('np.max(a, axis=1) : \n', np.max(a, axis=1))
print('np.max(a, axis=2) : \n', np.max(a, axis=2))
print()


a = np.arange(1,17).reshape(4,2,2)
print('(4,2,2) 배열 : \n', a)
print()
print('np.max(a) : \n', np.max(a))
print('np.max(a, axis=0) : \n', np.max(a, axis=0))
print('np.max(a, axis=1) : \n', np.max(a, axis=1))
print('np.max(a, axis=2) : \n', np.max(a, axis=2))
print()

a = np.arange(1,17).reshape(2,4,2)
print('(2,4,2) 배열 : \n', a)
print()
print('np.max(a) : \n', np.max(a))
print('np.max(a, axis=0) : \n', np.max(a, axis=0))
print('np.max(a, axis=1) : \n', np.max(a, axis=1))
print('np.max(a, axis=2) : \n', np.max(a, axis=2))
print()

a = np.arange(1,17).reshape(2,2,4)
print('(2,2,4) 배열 : \n', a)
print()
print('np.max(a) : \n', np.max(a))
print('np.max(a, axis=0) : \n', np.max(a, axis=0))
print('np.max(a, axis=1) : \n', np.max(a, axis=1))
print('np.max(a, axis=2) : \n', np.max(a, axis=2))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

np.max(a) : 
 8
np.max(a, axis=0) : 
 [[5 6]
 [7 8]]
np.max(a, axis=1) : 
 [[3 4]
 [7 8]]
np.max(a, axis=2) : 
 [[2 4]
 [6 8]]

(4,2,2) 배열 : 
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]

np.max(a) : 
 16
np.max(a, axis=0) : 
 [[13 14]
 [15 16]]
np.max(a, axis=1) : 
 [[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]
np.max(a, axis=2) : 
 [[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]

(2,4,2) 배열 : 
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]

np.max(a) : 
 16
np.max(a, axis=0) : 
 [[ 9 10]
 [11 12]
 [13 14]
 [15 16]]
np.max(a, axis=1) : 
 [[ 7  8]
 [15 16]]
np.max(a, axis=2) : 
 [[ 2  4  6  8]
 [10 12 14 16]]

(2,2,4) 배열 : 
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]

np.max(a) : 
 16
np.max(a, axis=0) : 
 [[ 9 10 11 12]
 [13 14 15 16]]
np.max(a, axis=1) : 
 [[ 5  6  7  8]
 [13 14 15 16]]
np.max(a, axis=2) : 
 [[ 4  8]
 [12 16]]


# kron연산 (추가)
kronecker 크로네커곱