In [1]:
import numpy as np

# 내적 (점곱) == ∙,  inner product, dot product

두벡터의 크기와 내각의 곱으로 구한다.  
또한 두 벡터의 내적은  

A = [a_1, a_2, ..., a_i]  
B = [b_1, b_2, ... , b_i] 일때   
A ∙ B = a_1 * b_1 + a_2 * b_2 + ... + a_i * b_i

In [2]:
a = np.array(np.arange(10, 15))
b = np.array(np.arange(4,9))
print('a : ', a)
print('b : ', b)

print('a @ b : ', a @ b)
print('np.dot(a,b) : ', np.dot(a,b))
print('np.inner(a,b) : ', np.inner(a,b))

a :  [10 11 12 13 14]
b :  [4 5 6 7 8]
a @ b :  370
np.dot(a,b) :  370
np.inner(a,b) :  370


# 외적 (가위곱) == ☓, cross product, (선형대수에서 외적 : outer product)
외적은 두 벡터를 지나는 평면과 수직인 벡터를 구하는것이다.
```
[1,4]   
[3,6]

=> 1 * 6 - 4 * 3
```

## outer product : 
A = [a,b,c].T
B = [d,e,f,g].T  
```
A ☓ B = AB =  
ad ae af ag  
bd be bf bg  
cd ce cf cg  
```
가 된다.

* np.cross() : 가위곱 => 수직인 벡터

* np.outer() : outer product 

In [3]:
a = np.array([1,4])
b = np.array([3,6])
print('np.cross(a,b) : ', np.cross(a,b))
print('이렇게 보는게 맞지 모르겠지만, (0,0,-6)과 같은것 같음')
print()

c = np.array([1,4,3])
d = np.array([3,4,5])
print('np.cross(c,d) : ', np.cross(c,d))

print('np.outer(c,d) : \n', np.outer(c, d))

np.cross(a,b) :  -6
이렇게 보는게 맞지 모르겠지만, (0,0,-6)과 같은것 같음

np.cross(c,d) :  [ 8  4 -8]
np.outer(c,d) : 
 [[ 3  4  5]
 [12 16 20]
 [ 9 12 15]]


# 행렬곱 dot product == @, .dot(), np.dot()
흔히 아는 행렬의 곱셈이다.

A = (m , p)  
B = (p , n)  
일때 A ∙ B 의 결과는 (m , n)이다.  

```
A = [[1,2],
     [3,4]]
     
B = [[5,6,7],
     [8,9,0]]
     
A ∙ B = 
1*5 + 2*8 | 1*6 + 2*9 | 1*7 + 2*0
3*5 + 3*8 | 3*6 + 3*9 | 3*7 + 3*0

```
     
## vdot 
행렬의 모든 원소를 1차원 벡터로 변환하여 내적을 구한다

In [4]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6,7], [8,9,0]])

print('a @ b : \n', a @ b)
print('a.dot(b) : \n', a.dot(b))
print('np.dot(a,b) : \n', np.dot(a,b))

a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
c = np.array([1,2,3,4])
d = np.array([5,6,7,8])


print('np.vdot(a,b) : ', np.vdot(a,b))
print('c @ d : ', c @ d)

a @ b : 
 [[21 24  7]
 [47 54 21]]
a.dot(b) : 
 [[21 24  7]
 [47 54 21]]
np.dot(a,b) : 
 [[21 24  7]
 [47 54 21]]
np.vdot(a,b) :  70
c @ d :  70


# 행렬 연산

## inner
행렬 A, B의 inner연산은 dot연산과 동일하다.

## outer
행렬의 outer연산은 행렬을 벡터로 만들어 이 벡터를 outer product한 것이다

## cross 
행울 기준으로 벡터간 cross연산을 함.

In [14]:
a = np.array([[1,2], [3,4]])

b = np.array([[3,2], [3,4]])

# print(np.inner(a,b))
print('a @ b : \n', a @ b)
print()
print('np.dot(a,b) : \n', np.dot(a,b))
print()
print('np.outer(a,b) : \n',np.outer(a,b))
print()

print(np.cross(a,b))

a @ b : 
 [[ 9 10]
 [21 22]]

np.dot(a,b) : 
 [[ 9 10]
 [21 22]]

np.outer(a,b) : 
 [[ 3  2  3  4]
 [ 6  4  6  8]
 [ 9  6  9 12]
 [12  8 12 16]]

[-4  0]
