In [7]:
import numpy as np
from pprint import pprint

# 벡터 산술연산

* `+` : np.add(a,b)
* `-` : np.subtract(a,b)
* `*` : np.multiply(a,b)
* `/` : np.divide(a,b)

In [3]:
a = np.array([1,2,3])
b = np.array([9,8,7])

print('a + b : ', a + b)
print('a - b : ', a - b)
print('a * b : ', a * b)
print('a / b : ', a / b)

a + b :  [10 10 10]
a - b :  [-8 -6 -4]
a * b :  [ 9 16 21]
a / b :  [0.11111111 0.25       0.42857143]


# 행렬과 스칼라 연산

행렬 * 스칼라

In [14]:
a = np.array(np.arange(1,10)).reshape(3,3)

print('a :')
pprint(a)
print()
print('a * 3:')
pprint(a * 3)
print()
print('a / 3:')
pprint(a / 3)
print()
print('a / 3:(정수처리)')
pprint(np.floor_divide(a, 3))

a :
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

a * 3:
array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

a / 3:
array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ],
       [2.33333333, 2.66666667, 3.        ]])

a / 3:(정수처리)
array([[0, 0, 1],
       [1, 1, 2],
       [2, 2, 3]])


# 대수법칙

* 결합법칙 
    * (A ± B) ± C = A ± (B ± C)
    * (A * B) * C = A * (B * C)
    
* 분배법칙
    * A * (B ± C) = A * B ± A * C
    * (B ± C) * A = A * B ± A * C

* 교환법칙
    * A ± B = B ± A
    * A * B = B * A
    
모든 원소