In [76]:
import numpy as np
from pprint import pprint

# 논리식

논리식 검색을 할때 논리식 배열과 검색을 하려는 배열의 행,열이 일치해야함.  
a < 4 => a 배열에서 4보다 작은 값의 위치에는 True, 
4보다 큰 값의 위치에는 False가 들어감.  

a[bool 배열]

**논리식 검새을 한 결과는 메모리를 공유하지 않는다!!**

* .nonzero() : 0이 아닌 원소의 인덱스를 리턴한다.

## 주의사항
논리연산은 and, or, not을 사용하지 못한다.  
대신 &, |, ~ 를 사용해야함.
0은 False로 취급됨.  => 즉 0 & 0 은 False임.



In [28]:
a = np.random.randn(4,5)
print('a < 0 : \n', a < 0)
print()
a[a < 0] = 999
print('a : \n', a)

a = np.array(np.arange(2, 10))
print('a.nonzero() : ', a.nonzero())

a = np.array(1)
print('np.logical_and(a , a) : ', np.logical_and(a , a))

a < 0 : 
 [[False False  True  True  True]
 [False False False  True  True]
 [ True  True False False  True]
 [ True  True False False False]]

a : 
 [[1.09403609e+00 7.60305835e-03 9.99000000e+02 9.99000000e+02
  9.99000000e+02]
 [1.13779590e+00 1.09384098e+00 6.16150720e-01 9.99000000e+02
  9.99000000e+02]
 [9.99000000e+02 9.99000000e+02 5.19241200e-01 8.92040788e-01
  9.99000000e+02]
 [9.99000000e+02 9.99000000e+02 1.11381442e+00 5.42582905e-01
  1.13641681e+00]]
a.nonzero() :  (array([0, 1, 2, 3, 4, 5, 6, 7]),)
np.logical_and(a , a) :  True


# 팬시검색

인덱스를 통해 배열을 검색한다.
**단 이때 메모리는 공유하지 않는다.**

In [32]:
a = np.array(np.arange(20, 40))
b = np.array(np.arange(9,13))
c = np.array([1,3,3,5])
print('a : ', a)
print('a[b] : ', a[b])
print('a[c] : ', a[c])
print('np.may_share_memory(a, a[b]) : ', np.may_share_memory(a, a[b]))
print('np.may_share_memory(a, a[:]) : ', np.may_share_memory(a, a[:]))

a :  [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
a[b] :  [29 30 31 32]
a[c] :  [21 23 23 25]
np.may_share_memory(a, a[b]) :  False
np.may_share_memory(a, a[:]) :  True


# 다차원 배열에서 팬시 검색

검색하려는 인덱스를 넣어 검색하면 된다.

In [43]:
a = np.array(np.arange(20, 40)).reshape(5, 4)
print('a : \n', a)
print()

print('a[[3,2]] : \n', a[[3,2]])
print()

print('a[[3,2], [0,1]] : \n', a[[3,2], [0,1]])    #3행 0열과, 2행 1열의 원소를 리턴한것임.

a : 
 [[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]

a[[3,2]] : 
 [[32 33 34 35]
 [28 29 30 31]]

a[[3,2], [0,1]] : 
 [32 29]


# 다차원 팬시 검색 (추가필요)

In [93]:
a = np.array(np.arange(20, 40)).reshape(5, 4)
print('a : \n', a)
print(a[[2,1], [3,3]])
print(a[[[2,1], [3,3]], [1,2]])

a : 
 [[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]
[31 27]
[[29 26]
 [33 34]]


# 팬시와 슬라이싱 혼용

In [54]:
a = np.array(np.arange(20, 40)).reshape(5, 4)
print('a : \n', a)
print(a[1:3, [2,3]])

a : 
 [[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]
[[26 27]
 [30 31]]


# 배열 축소 및 확대

## 차원  확대(c

In [88]:
a = np.array(np.arange(27)).reshape(9,3)
print(a.shape)
a = a[:, [[0,0,0], [1,1,1], [2,2,2, ]], np.newaxis]
print(a.shape)



(9, 3)
(9, 3, 3, 1)
