In [1]:
import numpy as np

### [1. 최대최소](#최대최소)
### [2. 대표값](#대표값)
### [3. 분산,표준편차](#분산,표준편차)
### [4. 상관계수,공분산](#상관계수와공분산)

# 최대 최소 처리

* np.max() : 최대값
* np.min() : 최소값
    * axis 지정 가능

* np.argmax() : 배열을 1차원으로 바꿔 가장 큰 인덱스를 리턴함
* np.argmin() : 배열을 1차원으로 바꿔 가장 작은 인덱스를 리턴함
    * axis 지정 가능

In [2]:
a = np.array([[1,2],[3,4]])
print(np.max(a))
print(np.max(a, axis=0))
print(np.max(a, axis=1))

b = np.arange(8)
np.random.shuffle(b)
b = b.reshape(2,4)

print('b : \n', b)
print('np.argmax(b) : ', np.argmax(b))
print('np.argmax(b, axis=0) : ', np.argmax(b, axis=0))
print('np.argmax(b, axis=1) : ', np.argmax(b, axis=1))
print('np.argmin(b) : ', np.argmin(b))

4
[3 4]
[2 4]
b : 
 [[0 3 1 4]
 [7 2 6 5]]
np.argmax(b) :  4
np.argmax(b, axis=0) :  [1 0 1 1]
np.argmax(b, axis=1) :  [3 0]
np.argmin(b) :  0


# 대표값

대표값으로는 평균, 중앙, 빈도수 등이 있다.

## 평균
* np.mean() : 평균값
* np.average() : 평균값

## 빈도수
* np.percentile() : 배열에서 백분율로 값 선택 (실제 존재하는 원소가 나오는게 아님)

## 중앙값
* np.median() : percentile()에서 50퍼센트 값을 선택한것과 동일함.
    * 값이 짝수면 중간 두개원소의 평균, 홀수면 중앙값을 리턴함.

    


In [3]:
a = np.arange(10).reshape(2,5)
print('a.mean() : ', a.mean())
print('np.mean(a, axis=0) : ', np.mean(a, axis=0))
print('np.percentile(a, 50) : ', np.percentile(a, 50))
print('np.median(a) : ', np.median(a))

a.mean() :  4.5
np.mean(a, axis=0) :  [2.5 3.5 4.5 5.5 6.5]
np.percentile(a, 50) :  4.5
np.median(a) :  4.5


# 분산표준편차

* np.var() : 분산을 구한다.
* np.std() : 표준편차를 구한다.

**만약 배열에 nan이 포함되어 있다면 nanvar(), nanstd()로 처리해야 한다.**

In [4]:
a = np.array([1,4,3,8,9,2,3])

print('np.var(a) : ', np.var(a))
print('분산 : ', np.sum(np.power(a - a.mean(), 2)) / (len(a)))
print('np.std(a) : ', np.std(a))
print('표준편차 : ', np.sqrt(np.var(a)) )

np.var(a) :  7.918367346938775
분산 :  7.918367346938775
np.std(a) :  2.813959371941744
표준편차 :  2.813959371941744


# 상관계수와공분산

두 수의 집합이 있을때 이 집합이 관계를 수치적으로 판단할 수 있음. 이 관계를 알아보는것을 상관계수라 함.

* np.cov() : 공분산 => 2개의 확률변수의 상관정도를 나타냄.
* np.corrcoef() : 상관계수 => **분자가 공분산**, 분모가 두 변수의 표준편차의 곱을 통해 구한다.

In [5]:
a = np.array([5,6,7,8])
b = np.array([1,3,4,5])

print('공분산 : \n', np.cov(a,b))
print('상관계수 : \n', np.corrcoef(a,b))

공분산 : 
 [[1.66666667 2.16666667]
 [2.16666667 2.91666667]]
상관계수 : 
 [[1.         0.98270763]
 [0.98270763 1.        ]]
