In [1]:
import numpy as np

# 정사각행렬

행과 열이 동일함.  

## 궤적 : Trace
주대각선 원소의 합  
.trace()

In [4]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print('a : ', a)

print('a.trace() : ', a.trace())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


# 대각행렬
정사각행렬일때 주대각선을 제외한 모든 원소가 0임

* .diagonal() : 주대각선의 원소만 뽑아냄
* np.diag() : 1차원 배열을 받아 대각행렬을 만들어냄
    * k값을 임의로 지정하여 대각선의 위치를 지정 가능
        * 주대각선 0을 기준으로 주대각선 보다 위에있는 대각선은 양수, 아래있는 대각선은 음수다


In [12]:
a = np.array([[1,0,0], [0,3,0], [0,0,5]])

print('a : \n', a)
print('a.diagonal() : ', a.diagonal())
print('np.diag([2,4,6]) : \n', np.diag([2,4,6]))
print('np.diag([2,4,6], k = 1) : \n', np.diag([2,4,6], k = 1))

a : 
 [[1 0 0]
 [0 3 0]
 [0 0 5]]
a.diagonal() :  [1 3 5]
np.diag([2,4,6]) : 
 [[2 0 0]
 [0 4 0]
 [0 0 6]]
np.diag([2,4,6], k = 1) : 
 [[0 2 0 0]
 [0 0 4 0]
 [0 0 0 6]
 [0 0 0 0]]


# 단위행렬(항등행렬)

대각행렬중 주대각선 원소가 모두 1인 행렬.  
이 행렬에 다른 행렬을 곱하여도 동일한 행렬 반환 (곱셈의 항등원)
* np.np.eye() 단위 행렬을 만든다
    * 이또한 역시 k값을 임의로 주어 다른 위치의 대각선으로도 가능함.

* np.identity() : 항등행렬을 만든다

In [19]:
a = np.eye(3,3)
print(a)
print()

b = np.eye(3,3, k = 1)
print(b)
print()

c = np.identity(3)
d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(c)
print(c @ d)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# 삼각행렬
주대각선 기준 위, 아래 값이 전부 0인경우  
* 하삼각행렬 : tril
    * np.tril() 메소드로 정사사각 행렬의 주대각선 밑 원소를 제외하고 모두 날려버림
        * k값을 통해 다른 위치의 대각선도 가능   
* 상삼각행렬 : triu
    * np.triu() 메소드로 정사각 행렬의 주대각선 위 원소를 제외하고 모두 날려버림
        * k값을 통해 다른 위치의 대각선도 가능


tril과 triu는 서로 전치관계이다

In [31]:
a = np.array(np.arange(1, 10)).reshape(3,3)
b = np.array(np.arange(10, 1, -1)).reshape(3,3)
c = np.array([1,2,3,4])

a_tril = np.tril(a)
a_tril2 = np.tril(a, k = -1)
b_triu = np.triu(b)
c = np.tril(c)
print('a_tril : \n', a_tril)
print('a_tril2 : \n ', a_tril2)
print('b_triu : \n', b_triu)
print('c : \n', c) #이런 방법도 있음

print('a_tril.T : \n' , a_tril.T)

a_tril : 
 [[1 0 0]
 [4 5 0]
 [7 8 9]]
a_tril2 : 
  [[0 0 0]
 [4 0 0]
 [7 8 0]]
b_triu : 
 [[10  9  8]
 [ 0  6  5]
 [ 0  0  2]]
c : 
 [[1 0 0 0]
 [1 2 0 0]
 [1 2 3 0]
 [1 2 3 4]]
a_tril.T : 
 [[1 4 7]
 [0 5 8]
 [0 0 9]]


# 영행렬

* np.zeros() : shape를 주어 0행렬을 만든다

* np.zeros_like() : 기존 행렬을 주어 그와 같은 shape의 행렬을 만든다

In [35]:
a = np.zeros((4,5))
b = np.zeros_like(np.array(
    [
        [1,2,3,4], 
        [5,6,7,8]
    ])
)

print('a : \n', a)
print()

print('b : \n', b)

a : 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

b : 
 [[0 0 0 0]
 [0 0 0 0]]


# 대칭행렬
주대각선 기준으로 위 아래 원소가 동일함.

# 반 대칭행렬
주대각 성분 기준 값은 같지만 부호가 반대임.



In [40]:
a = np.array([[1,2,3],[2,3,5], [3,5,6]])

print(a)
print()
print(a.T)
print()

b = np.array([[0,2,-3], [-2,0,5], [3,-5,0]])
print(b)
print()
print(b.T)
print()

[[1 2 3]
 [2 3 5]
 [3 5 6]]

[[1 2 3]
 [2 3 5]
 [3 5 6]]

[[ 0  2 -3]
 [-2  0  5]
 [ 3 -5  0]]

[[ 0 -2  3]
 [ 2  0 -5]
 [-3  5  0]]



# 치환행렬
단위행렬이나 행을 교환해 재구성 함.  
행변환을 한 단위 행렬과 행렬을 곱셈(dot product) 한다.

In [48]:
a = np.array(np.arange(1,10)).reshape(3,3)
b = np.array([[0,1,0], [1,0,0], [0,0,1]])
print(a)
print()

print(b)
print()

print(np.dot(a,b))
print()

print(a @ b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[0 1 0]
 [1 0 0]
 [0 0 1]]

[[2 1 3]
 [5 4 6]
 [8 7 9]]

[[2 1 3]
 [5 4 6]
 [8 7 9]]


# 직교행렬

자기 자신의 행렬과 전치 행렬을 행렬곱으로 계산한 결과
A @ A.T
**직교행렬의 전치행렬은 역행렬이다**

# 전치행렬

행렬의 모든 행과 열을 바꾸면 전치 행렬임.

In [49]:
a = np.array([[1,2],[3,4]])
print(a)

print(a.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
