In [2]:
import numpy as np

### [1. 논리연산](#논리연산)
### [2. 비교연산](#비교연산)
### [3. 수열](#수열)

# 논리연산

## AND연산
* np.bitwise_and() : 비트 and 연산
* `&`


* np.logical_and() : 일반 and 연산

## OR 연산
* np.bitwise_or() : 비트 or 연산
* `|`


* np.logical_or() : 일반 or 연산

## 배타적 논리합
* np.bitwise_xor() : 비트 xor 연산
* `^`

* np.logical_xor() : 일반 xor 연산


In [6]:
a = np.array(1)
b = np.array(3)
c = True
d = np.array([True, False])

print('a & b : ', a & b)
print('np.bitwise_and(a,b) : ', np.bitwise_and(a,b))
print('np.logical_and(c, d) : ', np.logical_and(c, d))
print('np.bitwise_xor(a,b) : ', np.bitwise_xor(a,b))

a & b :  1
np.bitwise_and(a,b) :  1
np.logical_and(c, d) :  [ True False]
np.bitwise_xor(a,b) :  2


# 비교연산

## less 연산 <
* np.less() : 작다
* `<`

## greater 연산 >
* np.greater() : 크다
* `>`

## 등호
* np.equal() : 등호연산
* `==`


* np.not_equal() : 같지 않다
* `!=`

## less_eaual <=
* np.less_equal() : 작거나 같다
* `<=`

## greate_equal >=
* np.greater_equal() : 크거나 같다
* `>=`

In [13]:
a = np.arange(16).reshape(4,4)
b = np.array([8,2,1,6])

print('a < b : \n', a < b)
print('np.less(a,b) : \n', np.less(a, b))
print('True의 갯수 세기 : ', (a<b).sum())

a < b : 
 [[ True  True False  True]
 [ True False False False]
 [False False False False]
 [False False False False]]
np.less(a,b) : 
 [[ True  True False  True]
 [ True False False False]
 [False False False False]
 [False False False False]]
True의 갯수 세기 :  4


# 수열

## 합
* np.sum() : 배열의 합 계산
* np.cumsum() : 누적 합계, 원배열 형상을 유지한다.
    * axis를 통해 축을 지정할 수 있다.
* np.nansum() : nan을 제외하고 계산한다.
* np.nancumsum() : nan을 제외하고 계산한다.

## 곱
* np.prod() : 배열의 곱 계산
* np.cumprod() : 누적 곱, 원배열 형상을 유지한다.
    * axis를 통해 축을 지정할 수 있다.
* np.nanprod() : nan을 빼고 계산한다.
* np.nancumprod() : nan을 빼고 계산한다.

In [16]:
a = np.arange(5)
b = np.arange(8).reshape(2,2,2)

print('np.sum(a) : ', np.sum(a))
print('np.cumsum(a) : ', np.cumsum(a))
print('b : \n', b)
print('np.sum(b, axis=0) : \n', np.sum(b, axis=0))
print('np.sum(b, axis=1) : \n', np.sum(b, axis=1))
print('np.sum(b, axis=2) : \n', np.sum(b, axis=2))

np.sum(a) :  10
np.cumsum(a) :  [ 0  1  3  6 10]
b : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
np.sum(b, axis=0) : 
 [[ 4  6]
 [ 8 10]]
np.sum(b, axis=1) : 
 [[ 2  4]
 [10 12]]
np.sum(b, axis=2) : 
 [[ 1  5]
 [ 9 13]]
