In [1]:
import numpy as np
from pprint import pprint

### [1. 실수절사/절상/반올림](#실수절사/절상/반올림)
### [2. 산술연산](#산술연산)
### [3. 부호,제곱,제곱근](#부호,제곱,제곱근)

# 실수절사/절상/반올림


## 절사함수
* np.fix() 
* np.trunc()
* np.floor()

## 반올림 함수
* np.round()
* np.around()

## 절상함수
* np.celi()



# 산술연산

## 더하기
np.add()
`+`

## 빼기
np.subtract()
`-`

## 곱하기
np.multiply
`*`

## 나누기
np.true_divide() : 실수값 리턴
`/`

np.floor_divide() : 정수값 리턴
`//`

### 몫, 나머지
* np.mod() : 나머지 리턴
* np.remainder() : 나머지 리턴
* np.divmod() : 몫, 나머지 리턴

## 역수
np.reciprocal()

In [2]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print('+ : ', np.add(a,b))
print('- : ', np.subtract(a,b))
print('* : ', np.multiply(a,b))
print('/ : ', np.true_divide(a,b))
print('// : ', np.floor_divide(a,b))

print('b mod a : ', np.mod(b,a))
print('b 를 a로 나눈 몫, 나머지 : ', np.divmod(b,a))
print('역수 구하기 : ', np.reciprocal(b.astype('float')))

+ :  [ 6  8 10 12]
- :  [-4 -4 -4 -4]
* :  [ 5 12 21 32]
/ :  [0.2        0.33333333 0.42857143 0.5       ]
// :  [0 0 0 0]
b mod a :  [0 0 1 0]
b 를 a로 나눈 몫, 나머지 :  (array([5, 3, 2, 2]), array([0, 0, 1, 0]))
역수 구하기 :  [0.2        0.16666667 0.14285714 0.125     ]


# 부호,제곱,제곱근

## 부호

* np.sign() : 부호를 1, -1로 표현한다
* np.negative() : -1를 곱한다
* np.positive() : 1을 곱한다
* np.absolute(), np.abs() : 절대값 리턴

## 제곱근
* np.square() : 제곱 처리
* np.power(a, n) : a의 n승
* np.sqrt() : 제곱근 처리

In [3]:
a = np.array([-1, 2, -3, 4])

print(np.sign(a))
print(np.negative(a))
print(np.positive(a))
print(np.abs(a))
print(np.absolute(a))
a = np.array([1, 2, 3, 4])

print(np.square(a))
print(np.power(a,3))
print(np.sqrt(a))

[-1  1 -1  1]
[ 1 -2  3 -4]
[-1  2 -3  4]
[1 2 3 4]
[1 2 3 4]
[ 1  4  9 16]
[ 1  8 27 64]
[1.         1.41421356 1.73205081 2.        ]
